-- {MOD} — keep SP at 100%
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Deliberately a SEPARATE mod. An earlier version bundled several of these
-- together, which meant you couldn't enable one without the others -- and
-- if one of them misbehaved (an un-closable menu, say) the whole bundle
-- became unusable. One mod, one job.

local CONFIG = {
    INTERVAL_MS = {INTERVAL_MS},
    TOGGLE_KEY = Key.{TOGGLE_KEY},
    START_ENABLED = {START_ENABLED},
}

local NAME = "{MOD}"
-- ---------------------------------------------------------------------
-- WHY EVERY UOBJECT OPERATION BELOW IS WRAPPED IN ExecuteInGameThread:
--
-- UE4SS runs Lua callbacks (key binds, LoopAsync) on its OWN thread. The
-- game's objects live on the GAME thread. Touching a UObject from the wrong
-- thread doesn't error -- it just quietly does nothing, or worse. That is
-- exactly the failure we kept hitting: mods that installed cleanly, logged
-- happily, and changed nothing at all.
--
-- Confirmed by reading working community mods for this game (DropRateScaling,
-- AutoRipost, Norescue): every one of them wraps its object work in
-- ExecuteInGameThread. The mods that DID work here by accident (movement
-- speed) were writing a value the engine re-reads every frame anyway, which
-- masked the problem.
-- ---------------------------------------------------------------------

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

-- ---------------------------------------------------------------------
-- Finding the player's stats. This is the part that broke last time.
--
-- HP, SP and Stamina are Gameplay Ability System attributes, living in
-- AttributeSet objects -- NOT fields on the character. (The character has
-- no .Health at all, which is why any mod doing `hero.Health = x` writes
-- into nothing and fails silently.) Verified in the game's SDK:
--     URODDefensiveAttributeSet : Health / MaxHealth     <- HP
--     URODAvatarAttributeSet    : Soul / MaxSoul         <- SP
--                                 Stamina / MaxStamina
--                                 EnhAtkSpeed (plain float)
--
-- My previous attempt assumed an AttributeSet's Outer was the
-- AbilitySystemComponent and walked to OwnerActor from there. In Unreal
-- the Outer is normally the OWNING ACTOR itself, so that check never
-- matched, no sets were ever found, and the mod did nothing at all --
-- quietly. Hence the belt-and-braces resolver below, which accepts either
-- shape and LOGS what it found, so a silent no-op can't happen twice.
--
-- Enemies own these same sets, so a set is only used if it resolves back
-- to the hero. Never blanket-apply to FindAllOf() results or you heal
-- every monster in the level.
-- ---------------------------------------------------------------------
local resolved = false

local function heroActor()
    local h = FindFirstOf("RODHeroCharacter")
    if h and h:IsValid() then return h end
    return nil
end

-- CONFIRMED BY THE DEBUG PROBE (2026-07-12): an AttributeSet's Outer IS the
-- owning actor. The probe printed 21 Defensive sets whose Outers were the
-- enemy Blueprints themselves (BP_E004001_C, ...) -- there is no
-- AbilitySystemComponent hop to make.
--
-- The probe also caught something nastier, which is why the nil-checks
-- below are written the way they are: UE4SS returns a DUMMY UObject for a
-- property that doesn't exist, not nil. `hero.Health` came back as
-- "UObject: 0000..." even though the character has no Health field at all.
-- So `if x ~= nil` is worthless as a guard -- it passes for fields that
-- aren't there, and the write then silently goes nowhere. Anything that
-- must be a NUMBER is therefore checked with type(v) == "number".
local function ownerOf(set)
    local owner
    pcall(function()
        local outer = set:GetOuter()
        if outer and outer:IsValid() then owner = outer end
    end)
    return owner
end

local function heroSet(className)
    local hero = heroActor()
    if not hero then return nil end
    local ok, sets = pcall(function() return FindAllOf(className) end)
    if not ok or not sets then return nil end
    for _, s in ipairs(sets) do
        local match = false
        pcall(function()
            if not s:IsValid() then return end
            local owner = ownerOf(s)
            if owner and owner:GetFullName() == hero:GetFullName() then match = true end
        end)
        if match then
            if not resolved then
                resolved = true
                log("found the hero's " .. className)
            end
            return s
        end
    end
    return nil
end

-- GAS recomputes CurrentValue from BaseValue + active effects, so write
-- both, and re-assert on a timer -- a single write gets overwritten.
local function setAttr(attr, value)
    pcall(function()
        attr.BaseValue = value
        attr.CurrentValue = value
    end)
end

local function readAttr(attr)
    local v
    pcall(function() v = attr.CurrentValue end)
    -- A dummy UObject (a property that doesn't exist) is not a value.
    if type(v) ~= "number" then return nil end
    return v
end

-- Write, then READ BACK. GAS recomputes CurrentValue from BaseValue plus
-- active effects, so a write can be accepted and then immediately reverted
-- -- which looks identical to "the mod isn't running". Verifying turns a
-- silent failure into a visible one.
local function writeVerified(attr, value)
    local after
    pcall(function()
        attr.BaseValue = value
        attr.CurrentValue = value
        after = attr.CurrentValue
    end)
    return type(after) == "number" and math.abs(after - value) < 0.01
end

-- SP is "Soul" in the code -- not a guess: the game's own SP bar widget is
-- URODHeroStatusSoulGaugeWidgetBase.
local enabled = CONFIG.START_ENABLED

local reportedOnce = false
local failedOnce = false

local function tick()
    ExecuteInGameThread(function()
        if not enabled then return end
        local set = heroSet("RODAvatarAttributeSet")
        if not set then
            if not failedOnce then
                failedOnce = true
                log("could not find the HERO's RODAvatarAttributeSet — the mod is doing nothing. "
                    .. "Run DebugProbe and send PlayerProbe.txt.")
            end
            return
        end
        local cur, max = readAttr(set.Soul), readAttr(set.MaxSoul)
        if not cur or not max or max <= 0 then
            if not failedOnce then
                failedOnce = true
                log("SP attributes are not readable as numbers — nothing to do. Run DebugProbe.")
            end
            return
        end
        if cur >= max then return end

        if writeVerified(set.Soul, max) then
            if not reportedOnce then
                reportedOnce = true
                log(string.format("SP restored %.0f -> %.0f (write verified — the mod IS working)", cur, max))
            end
        elseif not failedOnce then
            failedOnce = true
            log("SP write was ACCEPTED but did not stick — the game is recomputing it "
                .. "(a Gameplay Effect is overriding us). This needs a different approach; tell the toolkit.")
        end
    end)
end

RegisterKeyBind(CONFIG.TOGGLE_KEY, function()
    enabled = not enabled
    log(enabled and "SP lock ON" or "SP lock OFF")
end)

LoopAsync(CONFIG.INTERVAL_MS, function() tick(); return false end)
log("loaded — SP (Soul) restored to full whenever it drops")
