-- {MOD} — keep HP / SP / Stamina topped up (and optionally boost max Stamina)
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Covers four of the requests in one mod, because they're all the same
-- mechanism and running four separate loops over the same objects would
-- just be four times the overhead:
--     * HP      always 100%  (restored whenever it drops)
--     * SP      always 100%
--     * Stamina always 100%
--     * Stamina MAX multiplied (default 4x)
--
-- WHAT THESE STATS ACTUALLY ARE (this is why the naive approach fails):
-- Echoes of Aincrad uses Unreal's Gameplay Ability System. HP, SP and
-- Stamina are NOT plain floats on the character -- they're
-- FGameplayAttributeData living in AttributeSet objects, verified in the
-- game's own SDK:
--
--     URODDefensiveAttributeSet : Health / MaxHealth      <- HP
--     URODAvatarAttributeSet    : Soul   / MaxSoul        <- SP
--                                 Stamina / MaxStamina
--                                 MaxSpeed / MinSpeed
--
-- ("SP" is Soul -- confirmed by the game's own SoulGauge widgets:
--  URODHeroStatusSoulGaugeWidgetBase is the SP bar.)
--
-- Each attribute has a BaseValue and a CurrentValue. GAS recomputes
-- CurrentValue from active effects, so writing it once gets overwritten
-- the moment anything ticks. This mod writes both and RE-ASSERTS on a
-- timer, which is what makes it stick.
--
-- ENEMIES HAVE THESE SETS TOO. FindAllOf("RODDefensiveAttributeSet")
-- returns every monster's set as well as yours -- healing all of them
-- would make the game unwinnable. So the sets are matched back to the
-- hero through their owner chain, and anything not owned by the player is
-- left completely alone.

local CONFIG = {
    KEEP_HP_FULL      = {KEEP_HP_FULL},
    KEEP_SP_FULL      = {KEEP_SP_FULL},
    KEEP_STAMINA_FULL = {KEEP_STAMINA_FULL},

    -- 1.0 = leave max stamina alone. 4.0 = quadruple it.
    STAMINA_MAX_MULTIPLIER = {STAMINA_MAX_MULTIPLIER},

    -- 200ms: fast enough that a dip is invisible in play, cheap enough to
    -- run forever. (Stamina drains continuously while sprinting, so a
    -- slow poll would show a visible sawtooth.)
    INTERVAL_MS = {INTERVAL_MS},

    TOGGLE_KEY = Key.{TOGGLE_KEY},
    START_ENABLED = {START_ENABLED},
}

local NAME = "{MOD}"
local enabled = CONFIG.START_ENABLED
local baseMaxStamina = nil
local warned = false

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

-- Walk an AttributeSet back to the actor that owns it. The set's Outer is
-- the AbilitySystemComponent; the component's Outer (or OwnerActor) is the
-- character. Anything that doesn't land on the hero is someone else's.
local function ownedByHero(set, hero)
    local ok, owner = pcall(function()
        local outer = set:GetOuter()
        if not outer or not outer:IsValid() then return nil end
        -- ASC -> owning actor
        if outer.OwnerActor and outer.OwnerActor:IsValid() then return outer.OwnerActor end
        return outer:GetOuter()
    end)
    if not ok or not owner then return false end
    return owner:GetFullName() == hero:GetFullName()
end

local function heroSet(className, hero)
    local ok, sets = pcall(function() return FindAllOf(className) end)
    if not ok or not sets then return nil end
    for _, s in ipairs(sets) do
        local valid = false
        pcall(function() valid = s:IsValid() and ownedByHero(s, hero) end)
        if valid then return s end
    end
    return nil
end

-- Set both BaseValue and CurrentValue: CurrentValue is what the game
-- reads, BaseValue is what it recomputes CurrentValue FROM.
local function setAttr(attr, value)
    pcall(function()
        attr.BaseValue = value
        attr.CurrentValue = value
    end)
end

local function topUp(attr, maxAttr)
    local cur, max = nil, nil
    pcall(function()
        cur = attr.CurrentValue
        max = maxAttr.CurrentValue
    end)
    if not cur or not max or max <= 0 then return end
    if cur < max then setAttr(attr, max) end
end

local function tick()
    if not enabled then return end
    local hero = FindFirstOf("RODHeroCharacter")
    if not hero or not hero:IsValid() then return end

    if CONFIG.KEEP_HP_FULL then
        local def = heroSet("RODDefensiveAttributeSet", hero)
        if def then topUp(def.Health, def.MaxHealth) end
    end

    local av = heroSet("RODAvatarAttributeSet", hero)
    if av then
        if CONFIG.STAMINA_MAX_MULTIPLIER and CONFIG.STAMINA_MAX_MULTIPLIER ~= 1.0 then
            pcall(function()
                local curMax = av.MaxStamina.CurrentValue
                if curMax and curMax > 0 then
                    -- Remember the game's own max the first time we see a
                    -- value that isn't already ours, so the multiplier
                    -- can't compound on itself.
                    local target = (baseMaxStamina or curMax) * CONFIG.STAMINA_MAX_MULTIPLIER
                    if math.abs(curMax - target) > 0.01 then
                        if not baseMaxStamina or math.abs(curMax - baseMaxStamina) > 0.01 then
                            baseMaxStamina = curMax
                            target = curMax * CONFIG.STAMINA_MAX_MULTIPLIER
                        end
                        setAttr(av.MaxStamina, target)
                    end
                end
            end)
        end
        if CONFIG.KEEP_STAMINA_FULL then topUp(av.Stamina, av.MaxStamina) end
        if CONFIG.KEEP_SP_FULL then topUp(av.Soul, av.MaxSoul) end
    elseif not warned then
        warned = true
        log("could not find the hero's attribute sets yet — this is normal on the title screen")
    end
end

RegisterKeyBind(CONFIG.TOGGLE_KEY, function()
    enabled = not enabled
    log(enabled and "ON" or "OFF (stats left to the game)")
end)

LoopAsync(CONFIG.INTERVAL_MS, function()
    tick()
    return false
end)

log(string.format("loaded — HP:%s SP:%s Stamina:%s  maxStamina x%.1f  [%s]",
    tostring(CONFIG.KEEP_HP_FULL), tostring(CONFIG.KEEP_SP_FULL),
    tostring(CONFIG.KEEP_STAMINA_FULL), CONFIG.STAMINA_MAX_MULTIPLIER,
    enabled and "enabled" or "disabled"))
