-- {MOD} — fire the Riposte counter automatically when the window opens
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Grounded in the game's own SDK, not guesswork:
--     ARODHeroCharacter::bRiposteChance            (bool — the window is open)
--     ARODHeroCharacter::ActivateRiposteSlashSkill(ARODEnemyCharacter*)
--
-- Riposte is a timing move: the game raises bRiposteChance for a short
-- window after a parry, and you must input the counter inside it. This
-- watches that flag and fires the skill the instant it goes true, at the
-- nearest enemy in front of you.
--
-- Two things it deliberately does NOT do:
--   * It doesn't fire on a flag it hasn't seen GO true. It fires on the
--     rising edge, so one window = one counter, not a stream of calls into
--     a skill that's already running.
--   * It doesn't pick a target it can't see. If no enemy is within range,
--     it does nothing rather than swinging at air.

local CONFIG = {
    POLL_MS = {POLL_MS},
    -- Enemies further than this (cm) are not counter-attacked.
    MAX_RANGE = {MAX_RANGE},
    TOGGLE_KEY = Key.{TOGGLE_KEY},
    START_ENABLED = {START_ENABLED},
    VERBOSE = {VERBOSE},
}

local NAME = "{MOD}"
local enabled = CONFIG.START_ENABLED
local lastChance = false

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function nearestEnemy(hero)
    local here = hero:K2_GetActorLocation()
    local best, bestDist
    local ok, enemies = pcall(function() return FindAllOf("RODEnemyCharacter") end)
    if not ok or not enemies then return nil end
    for _, e in ipairs(enemies) do
        pcall(function()
            if not e:IsValid() then return end
            local l = e:K2_GetActorLocation()
            if l.X == 0 and l.Y == 0 and l.Z == 0 then return end
            local dx, dy, dz = l.X - here.X, l.Y - here.Y, l.Z - here.Z
            local d = math.sqrt(dx*dx + dy*dy + dz*dz)
            if d <= CONFIG.MAX_RANGE and (not bestDist or d < bestDist) then
                best, bestDist = e, d
            end
        end)
    end
    return best, bestDist
end

local function tick()
    if not enabled then return end
    ExecuteInGameThread(function()
        local hero = FindFirstOf("RODHeroCharacter")
        if not hero or not hero:IsValid() then return end

        local chance = false
        pcall(function() chance = hero.bRiposteChance == true end)

        -- RISING EDGE only. Firing every poll while the window is open
        -- would spam a skill that's already committed.
        if chance and not lastChance then
            local target, dist = nearestEnemy(hero)
            if target then
                local ok, fired = pcall(function()
                    return hero:ActivateRiposteSlashSkill(target)
                end)
                if CONFIG.VERBOSE then
                    log(ok and (fired and string.format("riposte fired (%.0fm)", (dist or 0)/100)
                                     or "riposte denied by the game")
                           or "ActivateRiposteSlashSkill errored")
                end
            elseif CONFIG.VERBOSE then
                log("riposte window open, but no enemy in range")
            end
        end
        lastChance = chance
    end)
end

RegisterKeyBind(CONFIG.TOGGLE_KEY, function()
    enabled = not enabled
    log(enabled and "auto-riposte ON" or "auto-riposte OFF")
end)

LoopAsync(CONFIG.POLL_MS, function() tick(); return false end)
log("loaded — counters fire automatically when the riposte window opens")
