-- {MOD} — Battle Healing passive (simplified, parameterized)
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
-- A CLEAN-ROOM SIMPLIFICATION of the Kirito_Battle_Healing example the
-- toolkit was given: same config surface (stage timings + HP/SP rates),
-- single file, no external config.lua -- edit CONFIG below or regenerate
-- from the toolkit with different values. The original mod remains the
-- richer implementation (file-based config, hot-reload, debug modes).
--
-- Mechanism: a repeating timer finds the hero character and adds a
-- percentage of Max HP/SP per tick, ramping through three stages the
-- longer you stay in combat -- everything pcall-guarded so a property
-- the game renames just logs instead of breaking the mod.

local CONFIG = {
    BATTLE_HEAL_DELAY   = {BATTLE_HEAL_DELAY},   -- seconds in combat before healing starts
    RECOVERY_INTERVAL_MS = {RECOVERY_INTERVAL_MS},

    STAGE_1_HP_RECOVERY = {STAGE_1_HP_RECOVERY}, -- % of max per tick
    STAGE_1_SP_RECOVERY = {STAGE_1_SP_RECOVERY},

    STAGE_2_START_SECONDS = {STAGE_2_START_SECONDS},
    STAGE_2_HP_RECOVERY   = {STAGE_2_HP_RECOVERY},
    STAGE_2_SP_RECOVERY   = {STAGE_2_SP_RECOVERY},

    STAGE_3_START_SECONDS = {STAGE_3_START_SECONDS},
    STAGE_3_HP_RECOVERY   = {STAGE_3_HP_RECOVERY},
    STAGE_3_SP_RECOVERY   = {STAGE_3_SP_RECOVERY},

    ENABLE_HP_RECOVERY = true,
    ENABLE_SP_RECOVERY = true,
    DEBUG_LOGS = false,
}

local NAME = "{MOD}"
local function log(msg) print(string.format("[%s] %s\n", NAME, tostring(msg))) end
local function dbg(msg) if CONFIG.DEBUG_LOGS then log(msg) end end

local combatSeconds = 0

local function rates()
    if combatSeconds >= CONFIG.STAGE_3_START_SECONDS then
        return CONFIG.STAGE_3_HP_RECOVERY, CONFIG.STAGE_3_SP_RECOVERY
    elseif combatSeconds >= CONFIG.STAGE_2_START_SECONDS then
        return CONFIG.STAGE_2_HP_RECOVERY, CONFIG.STAGE_2_SP_RECOVERY
    end
    return CONFIG.STAGE_1_HP_RECOVERY, CONFIG.STAGE_1_SP_RECOVERY
end

-- These stats are Gameplay Ability System attributes in AttributeSet
-- objects -- the character itself has NO .Health / .Stamina field, so the
-- original `hero.Health = x` in this script was writing into nothing and
-- failing silently. Verified against the game's SDK:
--     URODDefensiveAttributeSet : Health / MaxHealth   <- HP
--     URODAvatarAttributeSet    : Soul / MaxSoul       <- SP
--                                 Stamina / MaxStamina
-- Enemies own these same sets, so each one is matched back to the hero
-- through its owner before being touched.
local function heroSet(className, hero)
    local ok, sets = pcall(function() return FindAllOf(className) end)
    if not ok or not sets then return nil end
    for _, s in ipairs(sets) do
        local match = false
        pcall(function()
            if not s:IsValid() then return end
            local outer = s:GetOuter()
            if not outer or not outer:IsValid() then return end
            local owner = outer
            if outer.OwnerActor and outer.OwnerActor:IsValid() then owner = outer.OwnerActor end
            if owner:GetFullName() == hero:GetFullName() then match = true end
        end)
        if match then return s end
    end
    return nil
end

local function addAttr(attr, maxAttr, pct)
    pcall(function()
        local cur, max = attr.CurrentValue, maxAttr.CurrentValue
        if not cur or not max or max <= 0 or cur >= max then return end
        local v = math.min(max, cur + max * pct / 100)
        attr.BaseValue = v
        attr.CurrentValue = v
    end)
end

local function tick()
    local ok, err = pcall(function()
        local hero = FindFirstOf("RODHeroCharacter")
        if not hero or not hero:IsValid() then
            combatSeconds = 0
            return
        end
        -- Property names below are the common UE conventions; if the
        -- game uses different ones this logs once per session instead
        -- of erroring -- run with DEBUG_LOGS=true and check the UE4SS
        -- console, then adjust here (or use the toolkit's Lua function
        -- browser to find the real health component).
        local inCombat = true
        pcall(function() if hero.bInBattle ~= nil then inCombat = hero.bInBattle end end)
        if not inCombat then combatSeconds = 0; return end
        combatSeconds = combatSeconds + (CONFIG.RECOVERY_INTERVAL_MS / 1000)
        if combatSeconds < CONFIG.BATTLE_HEAL_DELAY then return end

        local hpRate, spRate = rates()
        if CONFIG.ENABLE_HP_RECOVERY then
            local def = heroSet("RODDefensiveAttributeSet", hero)
            if def then
                addAttr(def.Health, def.MaxHealth, hpRate)
                dbg(string.format("HP +%.1f%%", hpRate))
            end
        end
        if CONFIG.ENABLE_SP_RECOVERY then
            -- SP is "Soul" (the game's SP bar is URODHeroStatusSoulGaugeWidgetBase).
            -- The original code healed Stamina here and called it SP.
            local av = heroSet("RODAvatarAttributeSet", hero)
            if av then
                addAttr(av.Soul, av.MaxSoul, spRate)
                dbg(string.format("SP +%.1f%%", spRate))
            end
        end
    end)
    if not ok then dbg("tick error: " .. tostring(err)) end
end

LoopAsync(CONFIG.RECOVERY_INTERVAL_MS, function()
    tick()
    return false -- keep looping
end)

log("loaded — heal starts after " .. CONFIG.BATTLE_HEAL_DELAY .. "s of combat")
