-- {MOD} — open the Character Creator level
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Built from YOUR find: the UE4SS console's `Levels` command showed the
-- creator is its own level --
--     /Game/ROD/Maps/ROD/PL_CharacterMake
-- -- rather than a widget you can just open. So this travels to it.
--
-- READ THIS BEFORE YOU PRESS THE KEY:
-- Loading a level UNLOADS the one you're in. This is not a menu overlay --
-- it is a map change, exactly like the game's own transition to the
-- creator at the start of a playthrough. That means:
--   * you will leave the world you're standing in;
--   * anything unsaved is gone;
--   * the creator's own "done" flow may not know where to send you back
--     to, because you didn't arrive the way the game expects.
-- So the mod SAVES NOTHING and PROMISES NOTHING about the return trip. Use
-- it from somewhere you can afford to leave, and expect to reload a save
-- afterwards.
--
-- This is the honest state of it: it's an experiment you asked to try, and
-- the interesting question -- whether edits made in there carry back to
-- your character -- is exactly what testing will answer. The RETURN_LEVEL
-- option below lets you name the level to come back to, but whether the
-- creator hands control back cleanly is unknown until you try it.

local CONFIG = {
    OPEN_KEY = Key.{OPEN_KEY},
    LEVEL = "{LEVEL}",
    -- Require the key to be pressed twice within this window, so a stray
    -- press can't yank you out of the world. 0 disables the confirmation.
    CONFIRM_WINDOW_MS = {CONFIRM_WINDOW_MS},
}

local NAME = "{MOD}"
-- UE4SS key binds fire on UE4SS's OWN thread, not the game thread. UObject
-- work from the wrong thread silently does nothing -- which is why the EXP
-- grant, the town-chest fill and the enemy kill all "ran" and changed
-- nothing. Every working community mod for this game (DropRateScaling,
-- Norescue, AutoRipost) wraps its object work in ExecuteInGameThread; so do
-- these now.

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local armed = false

local function travel()
    local pc = FindFirstOf("RODInGamePlayerController") or FindFirstOf("PlayerController")
    if not pc or not pc:IsValid() then log("no player controller"); return end

    -- `open <level>` is the engine's own travel command -- the same thing
    -- the game does internally. Going through the console keeps us on the
    -- engine's code path instead of inventing one.
    local ok = pcall(function()
        pc:ConsoleCommand("open " .. CONFIG.LEVEL, false)
    end)
    if ok then
        log("travelling to " .. CONFIG.LEVEL .. " — the current world is being unloaded")
    else
        log("travel failed — ConsoleCommand was rejected")
    end
end

RegisterKeyBind(CONFIG.OPEN_KEY, function()
    ExecuteInGameThread(function()
        if CONFIG.CONFIRM_WINDOW_MS <= 0 then
            travel()
            return
        end
        if armed then
            armed = false
            travel()
            return
        end
        armed = true
        log("press again within " .. tostring(CONFIG.CONFIRM_WINDOW_MS / 1000)
            .. "s to LEAVE this world and load the Character Creator")
        ExecuteWithDelay(CONFIG.CONFIRM_WINDOW_MS, function()
            if armed then
                armed = false
                log("character-creator travel cancelled")
            end
        end)
    end)
end)

log("loaded — double-press the hotkey to load " .. CONFIG.LEVEL)
