-- {MOD} — dump treasure-chest world coordinates
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- WHY THIS EXISTS: the game ships 526 fixed chests in DT_FixTBoxTable,
-- and that table contains ONLY loot keys — no coordinates. Every level
-- JSON in the export was searched: the chest IDs (TB_*) appear nowhere
-- outside DT_FixTBoxTable and DT_ItemLotTable. The reason is in the
-- game's own SDK:
--
--     class ARODTBoxBase : public ARODGimmickBase
--         FName LocatorName;      <- the chest's ID (TB_Plains1_1_01_1)
--         bool  IsFixTBox;
--
-- A chest is a GIMMICK placed by a LOCATOR (ARODCMNGimmickLocator,
-- collected by ARODLocatorStorage). The locator actors are not in the
-- exported packages, so the coordinates cannot be read statically.
--
-- But they exist at RUNTIME, fully typed, and UE4SS can just ask.
-- That's what this does: no memory scanning, no signatures, no offsets
-- — it walks live UObjects and reads LocatorName + the actor's world
-- location straight off the object.
--
-- HOW TO USE
--   1. Install as a UE4SS Lua mod (Mods/{MOD}/Scripts/main.lua) and
--      enable it.
--   2. Play. Chests only exist while their level is STREAMED IN, so you
--      only capture what has loaded. Walk/fast-travel through the areas
--      you care about; the dumper re-scans on a timer and accumulates.
--   3. Press the dump hotkey (F10 by default) — or wait for the
--      auto-save — and it writes:
--          <game>/Binaries/Win64/ue4ss/ChestLocations.json
--   4. Upload that file on the toolkit's Build Dashboard. The Chests
--      section merges the coordinates and the Field Map draws the pins.
--
-- Everything found is accumulated across the session, so a full sweep of
-- both worlds produces one complete file. Chests already seen are not
-- overwritten by a later, worse read.

local CONFIG = {
    SCAN_INTERVAL_MS = {SCAN_INTERVAL_MS},
    AUTOSAVE_EVERY_SCANS = {AUTOSAVE_EVERY_SCANS},
    DUMP_KEY = Key.{DUMP_KEY},

    -- Also dump the gimmick locators themselves. They carry the same
    -- names and exist even for chests that haven't spawned their actor
    -- yet, so this usually captures MORE than the chest actors alone.
    INCLUDE_LOCATORS = {INCLUDE_LOCATORS},

    OUTPUT_FILE = "ChestLocations.json",
    VERBOSE = false,
}

local NAME = "{MOD}"
local found = {}     -- [locatorName] = {x=,y=,z=,source=}
local scans = 0

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function record(id, x, y, z, source)
    if not id or id == "" or id == "None" then return false end
    if found[id] then return false end
    found[id] = { x = x, y = y, z = z, source = source }
    if CONFIG.VERBOSE then
        log(string.format("%s @ %.1f, %.1f, %.1f (%s)", id, x, y, z, source))
    end
    return true
end

local function scan()
    scans = scans + 1
    local added = 0

    -- Chest actors currently spawned.
    local ok, boxes = pcall(function() return FindAllOf("RODTBoxBase") end)
    if ok and boxes then
        for _, box in ipairs(boxes) do
            local ok2 = pcall(function()
                if not box:IsValid() then return end
                local id = box.LocatorName:ToString()
                local loc = box:K2_GetActorLocation()
                if record(id, loc.X, loc.Y, loc.Z, "RODTBoxBase") then
                    added = added + 1
                end
            end)
            if not ok2 and CONFIG.VERBOSE then log("failed to read a TBox actor") end
        end
    end

    -- The locators that PLACE them. Their actor name is the locator
    -- name, which is what LocatorName resolves to.
    if CONFIG.INCLUDE_LOCATORS then
        local ok3, locs = pcall(function() return FindAllOf("RODCMNGimmickLocator") end)
        if ok3 and locs then
            for _, l in ipairs(locs) do
                pcall(function()
                    if not l:IsValid() then return end
                    local id = l:GetFName():ToString()
                    -- Only keep the ones that name a fixed chest.
                    if string.sub(id, 1, 3) == "TB_" then
                        local loc = l:K2_GetActorLocation()
                        if record(id, loc.X, loc.Y, loc.Z, "RODCMNGimmickLocator") then
                            added = added + 1
                        end
                    end
                end)
            end
        end
    end

    local total = 0
    for _ in pairs(found) do total = total + 1 end
    if added > 0 then
        log(string.format("+%d new (%d total captured this session)", added, total))
    end

    if CONFIG.AUTOSAVE_EVERY_SCANS > 0 and scans % CONFIG.AUTOSAVE_EVERY_SCANS == 0 and total > 0 then
        save()
    end
end

function save()
    local parts = {}
    local total = 0
    for id, p in pairs(found) do
        total = total + 1
        parts[#parts + 1] = string.format(
            '  {"chestId":"%s","x":%.3f,"y":%.3f,"z":%.3f,"source":"%s"}', id, p.x, p.y, p.z, p.source)
    end
    -- Hand-rolled JSON: UE4SS Lua has no json library by default, and a
    -- flat array of flat records doesn't justify vendoring one.
    local json = '{\n "capturedBy": "' .. NAME .. '",\n "count": ' .. total ..
                 ',\n "chests": [\n' .. table.concat(parts, ",\n") .. '\n ]\n}\n'

    local f, err = io.open(CONFIG.OUTPUT_FILE, "w")
    if not f then
        log("could not open " .. CONFIG.OUTPUT_FILE .. ": " .. tostring(err))
        return
    end
    f:write(json)
    f:close()
    log(string.format("wrote %d chest coordinates -> %s (upload this on the Build Dashboard)",
        total, CONFIG.OUTPUT_FILE))
end

RegisterKeyBind(CONFIG.DUMP_KEY, function()
    save()
end)

LoopAsync(CONFIG.SCAN_INTERVAL_MS, function()
    scan()
    return false
end)

log("loaded — walk the world; chests are captured as their levels stream in. Press the dump key to write the file.")
