-- {MOD} — diagnostic probe: find out WHY the other mods do nothing
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Several mods (EXP grant, always-full HP/SP/Stamina, town chest 999,
-- inventory slots) install cleanly and then do nothing at all. That's the
-- worst failure mode there is: no error, no crash, no clue. It means one
-- of my assumptions about what UE4SS can reach in THIS game is wrong -- and
-- I've been guessing at which one.
--
-- So: stop guessing. This mod doesn't change anything. It walks every
-- assumption those mods depend on, one at a time, and reports exactly which
-- ones hold and which don't:
--
--   * Can we find the hero / player controller / player state at all?
--   * What are their REAL class names? (A wrong name = FindFirstOf returns
--     nil = every mod using it silently no-ops. battle_healing.lua looked
--     for "ROHeroCharacter" for months -- the D was missing.)
--   * Are the AttributeSets reachable, and WHO owns them? (My HP mod
--     assumed the set's Outer is the AbilitySystemComponent. If it's the
--     actor instead, the resolver never matches and the loop does nothing.)
--   * Can we READ a GAS attribute (Health.CurrentValue)? Can we WRITE one
--     and does it STAY written a second later?
--   * Are the game's own functions actually CALLABLE from Lua
--     (AddCol worked -- does DebugAddHeroExp exist and accept a call)?
--   * Does the item manager exist and do its arrays have entries?
--   * Does RegisterHook succeed on the town chest's open event?
--
-- Press the key, then send back the log (or PlayerProbe.txt, written next
-- to the UE4SS dll). Every broken mod gets fixed from facts instead of
-- another guess.

local CONFIG = {
    PROBE_KEY = Key.{PROBE_KEY},
    -- Write findings to a file as well as the console, so nothing is lost
    -- when the log scrolls.
    OUTPUT_FILE = "PlayerProbe.txt",
    -- Actually try a WRITE to Health and see if it sticks. Safe: it writes
    -- the value back to what it already was.
    TEST_WRITES = {TEST_WRITES},
}

local NAME = "{MOD}"
local lines = {}

local function out(m)
    print(string.format("[%s] %s\n", NAME, tostring(m)))
    lines[#lines + 1] = tostring(m)
end

local function try(label, fn)
    local ok, res = pcall(fn)
    if ok then
        out(string.format("  OK    %s = %s", label, tostring(res)))
        return res
    end
    out(string.format("  FAIL  %s  (%s)", label, tostring(res)))
    return nil
end

-- Try several class names for the same thing. This is how we catch a name
-- being subtly wrong -- which is invisible from inside a mod that just
-- silently finds nothing.
local function findAny(names)
    for _, n in ipairs(names) do
        local ok, obj = pcall(function() return FindFirstOf(n) end)
        if ok and obj and obj:IsValid() then
            return obj, n
        end
    end
    return nil, nil
end

local function countOf(name)
    local ok, arr = pcall(function() return FindAllOf(name) end)
    if not ok or not arr then return 0 end
    return #arr
end

local function probe()
    lines = {}
    out("================ ROD PROBE ================")

    -- 1. The actors every mod depends on -----------------------------
    out("[1] Core objects")
    local hero, heroName = findAny({
        "RODHeroCharacter", "RODAvatarCharacter", "RODPlayerCharacter",
        "RODCharacterBase", "ROHeroCharacter",
    })
    if hero then
        out("  hero FOUND via FindFirstOf(\"" .. heroName .. "\")")
        try("hero:GetFullName()", function() return hero:GetFullName() end)
        try("hero class", function() return hero:GetClass():GetFName():ToString() end)
        try("hero.CharacterMovement", function()
            return hero.CharacterMovement and hero.CharacterMovement:GetFullName() or "nil"
        end)
        -- This is what the WORKING speed mod uses -- if it reads, property
        -- access is fine and the problem is elsewhere.
        try("hero.CharacterMovement.MaxWalkSpeed (speed mod works, so this should read)",
            function() return hero.CharacterMovement.MaxWalkSpeed end)
        -- Does the character expose stats directly? (I claim it does NOT.)
        try("hero.Health (expected: FAIL -- proves stats are NOT on the character)",
            function() return hero.Health end)
    else
        out("  !! HERO NOT FOUND under ANY known name. Every stat mod would silently do nothing.")
    end

    local pc, pcName = findAny({ "RODInGamePlayerController", "RODPlayerControllerBase", "PlayerController" })
    out(pc and ("  player controller FOUND via \"" .. pcName .. "\"") or "  !! player controller NOT FOUND")
    if pc then try("pc class", function() return pc:GetClass():GetFName():ToString() end) end

    local ps, psName = findAny({ "RODPlayerState", "RODPlayerStateBase" })
    out(ps and ("  player state FOUND via \"" .. psName .. "\"") or "  !! player state NOT FOUND")
    if ps then
        -- Col works, so this read should succeed. It's our control group:
        -- if Col reads and Health doesn't, the difference is the answer.
        try("ps.Col (the Col mod WORKS, so this is the control)", function() return ps.Col end)
    end

    -- 2. Attribute sets: the prime suspect ---------------------------
    out("")
    out("[2] Gameplay Ability System attribute sets")
    for _, cls in ipairs({ "RODDefensiveAttributeSet", "RODAvatarAttributeSet",
                           "RODHeroAttributeSet", "RODOffensiveAttributeSet" }) do
        local n = countOf(cls)
        out(string.format("  FindAllOf(\"%s\") -> %d object(s)%s", cls, n,
            n == 0 and "   <-- if 0, the class name is wrong or they're not exposed" or ""))
    end

    -- WHO OWNS THEM. This is the assumption that most likely broke the HP mod.
    local ok, sets = pcall(function() return FindAllOf("RODDefensiveAttributeSet") end)
    if ok and sets and #sets > 0 and hero then
        out("  owner chain of each Defensive set (looking for the hero):")
        local heroFull = hero:GetFullName()
        for i, s in ipairs(sets) do
            if i > 6 then out("    ... (" .. (#sets - 6) .. " more)"); break end
            local outerName, outerClass, ownerActor = "?", "?", "?"
            pcall(function()
                local o = s:GetOuter()
                outerName = o and o:GetFullName() or "nil"
                outerClass = o and o:GetClass():GetFName():ToString() or "nil"
                if o and o.OwnerActor and o.OwnerActor:IsValid() then
                    ownerActor = o.OwnerActor:GetFullName()
                end
            end)
            local isHero = (outerName == heroFull) or (ownerActor == heroFull)
            out(string.format("    [%d] Outer=%s (%s)", i, outerClass, outerName))
            out(string.format("        OwnerActor=%s   %s", ownerActor,
                isHero and "<<< THIS IS THE HERO'S SET" or ""))
        end
    end

    -- 3. Can we actually read/write an attribute? --------------------
    out("")
    out("[3] Attribute read / write")
    if ok and sets and #sets > 0 then
        local s = sets[1]
        try("set.Health (struct exists?)", function() return s.Health ~= nil end)
        local cur = try("set.Health.CurrentValue", function() return s.Health.CurrentValue end)
        try("set.Health.BaseValue", function() return s.Health.BaseValue end)
        try("set.MaxHealth.CurrentValue", function() return s.MaxHealth.CurrentValue end)

        if CONFIG.TEST_WRITES and cur then
            -- Write the SAME value back: harmless, but tells us whether
            -- writes are accepted at all.
            out("  attempting a no-op write (Health = its own value)...")
            try("write Health.CurrentValue", function()
                s.Health.CurrentValue = cur
                return s.Health.CurrentValue
            end)
        end
    else
        out("  skipped -- no attribute sets to test")
    end

    -- 4. Are the game's own functions callable? ----------------------
    out("")
    out("[4] Function calls (AddCol WORKS -- so which others do?)")
    if ps then
        try("ps:AddCol(0)  [known-good control]", function() ps:AddCol(0); return "called" end)
    end
    if pc then
        try("pc:DebugAddHeroExp(0)", function() pc:DebugAddHeroExp(0); return "called" end)
        try("pc:ServerDebugAddHeroExp(0)", function() pc:ServerDebugAddHeroExp(0); return "called" end)
        try("pc:OpenDirectingMapMenu exists?", function()
            return pc.OpenDirectingMapMenu ~= nil
        end)
    end

    -- Where does the player's EXP/level actually live?
    local ui = findAny({ "RODUserInfo" })
    if ui then
        try("UserInfo.Level", function() return ui.Level end)
        try("UserInfo.Experience", function() return ui.Experience end)
    else
        out("  RODUserInfo NOT found -- the level/EXP mod had nothing to write to")
    end

    -- 5. Inventory ---------------------------------------------------
    out("")
    out("[5] Item manager (the town-chest 999 mod depends on this)")
    local im = findAny({ "RODAvatarItemManager", "RODItemManager" })
    if im then
        try("im.Items count", function() return #im.Items end)
        try("im.MaterialItems count", function() return #im.MaterialItems end)
        try("im.EquipmentItems count", function() return #im.EquipmentItems end)
        try("first item's Num", function() return im.Items[1].Num end)
        try("first item's ItemId", function() return im.Items[1].ItemId end)
    else
        out("  !! RODAvatarItemManager NOT FOUND -- explains why the 999 mod did nothing")
    end

    -- 6. Hooks -------------------------------------------------------
    out("")
    out("[6] Hooks")
    local hookOk = pcall(function()
        RegisterHook("/Script/ROD.RODChestBase:BP_OnOpenUI", function() end)
    end)
    out("  RegisterHook RODChestBase:BP_OnOpenUI -> " .. (hookOk and "accepted" or "REJECTED")
        .. (hookOk and "" or "   <-- explains the town-chest mod"))

    -- 7. Enemies -----------------------------------------------------
    out("")
    out("[7] Enemies (for the kill-nearby / EXP-by-death idea)")
    local n = countOf("RODEnemyCharacter")
    out(string.format("  FindAllOf(\"RODEnemyCharacter\") -> %d", n))
    if n > 0 then
        local okE, enemies = pcall(function() return FindAllOf("RODEnemyCharacter") end)
        if okE and enemies[1] then
            try("enemy:GetFullName()", function() return enemies[1]:GetFullName() end)
            try("enemy.KillingBlow exists?", function() return enemies[1].KillingBlow ~= nil end)
            try("enemy:IsDead4Avatar exists?", function() return enemies[1].IsDead4Avatar ~= nil end)
        end
    end

    out("==========================================")

    local f = io.open(CONFIG.OUTPUT_FILE, "w")
    if f then
        f:write(table.concat(lines, "\n") .. "\n")
        f:close()
        out("written to " .. CONFIG.OUTPUT_FILE .. " — send this back and every broken mod gets fixed from facts")
    end
end

RegisterKeyBind(CONFIG.PROBE_KEY, probe)

print(string.format("[%s] loaded — press the probe key IN GAME (not the title screen) to dump findings\n", NAME))
