-- {MOD} — scale item drop rates
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Edits the game's DataTables LIVE, which is the technique the community's
-- DropRateScaling mod uses and which I had wrongly concluded was impossible:
--     local dt = StaticFindObject("/Game/....DT_ItemLotTable.DT_ItemLotTable")
--     local rows = dt:GetRowMap()
--
-- HOW DROPS ACTUALLY WORK HERE (verified against the exported tables):
--   DT_RewardLotTable  -- per enemy: RewardParams -> RewardLotParams, a list
--                         of {LotItemKey, Weight}. Crucially one of those
--                         entries is LotItemKey "None" -- that's the NOTHING
--                         slot, and its weight is usually the biggest
--                         (Boar01: Material 1, Food 2, None 12).
--   DT_ItemLotTable    -- per lot: ItemLotParams -> {Item{Category,ItemId,Num}, Weight}
--
-- So the honest way to raise drop rates is NOT to inflate item weights (which
-- only changes WHICH item you get, not WHETHER you get one) -- it's to shrink
-- the "None" weight. That's the difference between a mod that feels like it
-- works and one that does.
--
-- The original values are SNAPSHOTTED on first apply, so re-applying scales
-- from the game's numbers rather than compounding on its own output.

local CONFIG = {
    -- Divide the "no drop" weight by this. 1 = off, 12 = Boar01 always drops.
    NO_DROP_DIVISOR = {NO_DROP_DIVISOR},
    -- Multiply every ITEM weight (changes the mix, not the drop chance).
    ITEM_WEIGHT_MULTIPLIER = {ITEM_WEIGHT_MULTIPLIER},
    -- Multiply the quantity rolled per drop.
    QUANTITY_MULTIPLIER = {QUANTITY_MULTIPLIER},

    APPLY_KEY = Key.{APPLY_KEY},
    RETRY_MS = {RETRY_MS},
    RETRIES = {RETRIES},
}

local REWARD_DT = "/Game/ROD/DataAssets/WorldAdmin/DT_RewardLotTable.DT_RewardLotTable"
local ITEM_DT   = "/Game/ROD/DataAssets/WorldAdmin/DT_ItemLotTable.DT_ItemLotTable"

local NAME = "{MOD}"
local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function isValid(o)
    if o == nil then return false end
    local v = false
    pcall(function() v = o:IsValid() end)
    return v
end

local snapshot = {}   -- original weights, so re-apply never compounds

local function scaleRewardTable()
    local dt = StaticFindObject(REWARD_DT)
    if not isValid(dt) then return 0 end
    local rows
    if not pcall(function() rows = dt:GetRowMap() end) or type(rows) ~= "table" then return 0 end

    local n = 0
    for key, row in pairs(rows) do
        pcall(function()
            local params = row.RewardParams
            if not params then return end
            for i = 1, #params do
                local lots = params[i].RewardLotParams
                if lots then
                    for j = 1, #lots do
                        local entry = lots[j]
                        local lotKey = tostring(entry.LotItemKey)
                        local w = tonumber(entry.Weight)
                        if w then
                            local id = string.format("%s|%d|%d", tostring(key), i, j)
                            if snapshot[id] == nil then snapshot[id] = w end
                            local base = snapshot[id]

                            if lotKey == "None" then
                                -- THE nothing slot. Shrinking this is what
                                -- actually raises the chance of any drop.
                                local nw = math.max(0, math.floor(base / CONFIG.NO_DROP_DIVISOR))
                                entry.Weight = nw
                            else
                                entry.Weight = math.floor(base * CONFIG.ITEM_WEIGHT_MULTIPLIER)
                            end
                            n = n + 1
                        end
                    end
                end
            end
        end)
    end
    return n
end

local function scaleItemTable()
    local dt = StaticFindObject(ITEM_DT)
    if not isValid(dt) then return 0 end
    local rows
    if not pcall(function() rows = dt:GetRowMap() end) or type(rows) ~= "table" then return 0 end

    local n = 0
    for key, row in pairs(rows) do
        pcall(function()
            local params = row.ItemLotParams
            if not params then return end
            for i = 1, #params do
                local p = params[i]
                local num = p.Item and tonumber(p.Item.Num)
                if num and CONFIG.QUANTITY_MULTIPLIER ~= 1 then
                    local id = string.format("q|%s|%d", tostring(key), i)
                    if snapshot[id] == nil then snapshot[id] = num end
                    p.Item.Num = math.max(1, math.floor(snapshot[id] * CONFIG.QUANTITY_MULTIPLIER))
                    n = n + 1
                end
            end
        end)
    end
    return n
end

local function apply(left)
    ExecuteInGameThread(function()
        local a = scaleRewardTable()
        local b = scaleItemTable()
        if a > 0 or b > 0 then
            log(string.format("scaled %d reward weight(s), %d quantity field(s) "
                .. "[no-drop /%.1f, item weight x%.1f, quantity x%.1f]",
                a, b, CONFIG.NO_DROP_DIVISOR, CONFIG.ITEM_WEIGHT_MULTIPLIER,
                CONFIG.QUANTITY_MULTIPLIER))
            return
        end
        if left > 0 then
            -- The tables aren't loaded at the title screen.
            ExecuteWithDelay(CONFIG.RETRY_MS, function() apply(left - 1) end)
        else
            log("drop tables never loaded — enter a save and press the apply key")
        end
    end)
end

RegisterKeyBind(CONFIG.APPLY_KEY, function() apply(CONFIG.RETRIES) end)
ExecuteWithDelay(CONFIG.RETRY_MS, function() apply(CONFIG.RETRIES) end)
log("loaded — drop rates will be scaled once the tables load")
