-- {MOD} — list the nearest loaded enemies (and optionally dump them)
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Enemies only exist while their streaming cell is loaded -- the same rule
-- that makes chest sweeping awkward. So this reports what's ACTUALLY in
-- memory right now, with distances, rather than what the database says
-- should be somewhere.
--
-- It reads each enemy's HP straight from its Gameplay Ability System
-- attribute set (URODDefensiveAttributeSet.Health / MaxHealth), matched
-- back to that specific enemy by owner -- never a blanket FindAllOf, which
-- would happily hand you the player's set or another monster's.
--
-- The optional dump writes EnemyLocations.json in the same shape as the
-- gimmick dumps, so it can be uploaded on the Build Dashboard later if we
-- decide to map spawn points.

local CONFIG = {
    LIST_KEY = Key.{LIST_KEY},
    DUMP_KEY = Key.{DUMP_KEY},
    MAX_RESULTS = {MAX_RESULTS},
    OUTPUT_FILE = "EnemyLocations.json",
}

local NAME = "{MOD}"
local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function healthOf(enemy)
    local cur, max
    local ok, sets = pcall(function() return FindAllOf("RODDefensiveAttributeSet") end)
    if not ok or not sets then return nil end
    local full = enemy:GetFullName()
    for _, s in ipairs(sets) do
        local mine = false
        pcall(function()
            local o = s:GetOuter()
            mine = o and o:IsValid() and o:GetFullName() == full
        end)
        if mine then
            pcall(function()
                cur = tonumber(s.Health.CurrentValue)
                max = tonumber(s.MaxHealth.CurrentValue)
            end)
            break
        end
    end
    return cur, max
end

local function collect()
    local out = {}
    local hero = FindFirstOf("RODHeroCharacter")
    if not hero or not hero:IsValid() then return out end
    local here = hero:K2_GetActorLocation()

    local ok, enemies = pcall(function() return FindAllOf("RODEnemyCharacter") end)
    if not ok or not enemies then return out end

    for _, e in ipairs(enemies) do
        pcall(function()
            if not e:IsValid() then return end
            local full = e:GetFullName()
            -- Class Default Objects are templates, not spawned monsters.
            if string.find(full, "Default__", 1, true) then return end
            local l = e:K2_GetActorLocation()
            if l.X == 0 and l.Y == 0 and l.Z == 0 then return end

            local dx, dy, dz = l.X - here.X, l.Y - here.Y, l.Z - here.Z
            local cur, max = healthOf(e)
            out[#out + 1] = {
                class = e:GetClass():GetFName():ToString(),
                name = e:GetFName():ToString(),
                x = l.X, y = l.Y, z = l.Z,
                dist = math.sqrt(dx*dx + dy*dy + dz*dz),
                hp = cur, maxHp = max,
            }
        end)
    end
    table.sort(out, function(a, b) return a.dist < b.dist end)
    return out
end

RegisterKeyBind(CONFIG.LIST_KEY, function()
    ExecuteInGameThread(function()
        local list = collect()
        if #list == 0 then log("no enemies loaded right now"); return end
        log(string.format("%d enemy(s) loaded — nearest %d:", #list, math.min(#list, CONFIG.MAX_RESULTS)))
        for i = 1, math.min(#list, CONFIG.MAX_RESULTS) do
            local e = list[i]
            log(string.format("  %2d. %-22s %6.0fm  HP %s/%s", i, e.class, e.dist / 100,
                tostring(e.hp and math.floor(e.hp) or "?"),
                tostring(e.maxHp and math.floor(e.maxHp) or "?")))
        end
    end)
end)

RegisterKeyBind(CONFIG.DUMP_KEY, function()
    ExecuteInGameThread(function()
        local list = collect()
        local parts = {}
        for _, e in ipairs(list) do
            parts[#parts + 1] = string.format(
                '  {"class":"%s","name":"%s","x":%.3f,"y":%.3f,"z":%.3f,"hp":%s,"maxHp":%s}',
                e.class, e.name, e.x, e.y, e.z,
                e.hp and string.format("%.1f", e.hp) or "null",
                e.maxHp and string.format("%.1f", e.maxHp) or "null")
        end
        local f = io.open(CONFIG.OUTPUT_FILE, "w")
        if not f then log("could not write " .. CONFIG.OUTPUT_FILE); return end
        f:write('{\n "capturedBy": "' .. NAME .. '",\n "count": ' .. #list ..
                ',\n "enemies": [\n' .. table.concat(parts, ",\n") .. '\n ]\n}\n')
        f:close()
        log(string.format("wrote %d enemies -> %s", #list, CONFIG.OUTPUT_FILE))
    end)
end)

log("loaded — list key prints the nearest enemies; dump key writes them to JSON")
