-- {MOD} — dump ALL gimmick locations (chests, arks, seals, trinkets, lore…)
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- v2 of ChestLocatorDump. Same idea, much wider net: every gimmick in the
-- game derives from ARODGimmickBase, so one sweep captures them all
-- instead of walking the world once per type.
--
-- WHAT IT CAPTURES (classes confirmed in the game's own SDK, not guessed):
--   RODTBoxBase              treasure chests            id: LocatorName
--   RODChestBase             chests (incl. town chests) id: LocatorName/ID
--   RODSubQuestGimmickBase   side-quest trinkets        id: ID + SubQuestID
--   RODSealedBase            seals / magical seals      id: ID
--   RODSealedArkBase         sealed arks                id: ID
--   RODArkBase               arks                       id: ID
--   RODTipsGimmickBase       lore / tips                id: ID
--   RODGiftPillar            gift pillars               id: ID
--   RODMapPinBase            map pins                   id: ID
--   RODQuestTerminalBase     quest terminals            id: ID
--   RODActivatableTerminalBase  warp/safe terminals     id: ID
--   RODAccessibleGimmickBase    the generic base — CATCHES THE TOWN
--                               SHOP GIMMICKS (Smithy, Item Seller):
--                               they're accessible gimmicks, so they
--                               come through here even though the SDK
--                               gives them no class of their own.
--   RODSignPost, RODDungeonGuide, RODBarrierBase, RODWallDoor,
--   RODGateDoorBase, RODBreakableGimmickBase, RODSequenceCtrlGimmickBase
--
-- CONTEXT CAPTURED WITH EACH ONE (this is the part that was missing):
--   * chunk / level  -- parsed from the actor's OWN full name, so it's the
--                       level the gimmick actually lives in, not wherever
--                       the player happened to be standing. That's the
--                       difference between "I think this was the Plains"
--                       and knowing.
--   * questId        -- URODQuestManager:GetQuestID() at capture time.
--   * seenAt         -- the player's position when it was first seen, so a
--                       sweep can be retraced.
--
-- HOW TO USE
--   1. Install as a UE4SS Lua mod, enable it, and play normally.
--   2. Gimmicks only exist while their streaming CELL is loaded -- and a
--      named area spans several cells (standing in the Plains safe area
--      captured 3 of its 8 chests, not 8). So walk the ground, don't just
--      visit the area.
--   3. Press F10 (or wait for autosave) -> GimmickLocations.json next to
--      the UE4SS dll. Upload it on the Build Dashboard. Uploads MERGE, so
--      many short sessions add up to one complete map.

local CONFIG = {
    -- 20s: gimmick sweeps are heavier than the chest-only scan, and
    -- nothing here is time-critical -- a chest doesn't move.
    SCAN_INTERVAL_MS = {SCAN_INTERVAL_MS},
    AUTOSAVE_EVERY_SCANS = {AUTOSAVE_EVERY_SCANS},
    DUMP_KEY = Key.{DUMP_KEY},

    OUTPUT_FILE = "GimmickLocations.json",

    -- Log every new capture as it happens (id + type + chunk).
    VERBOSE = {VERBOSE},
}

local NAME = "{MOD}"

-- class -> the short "kind" recorded in the output. Order matters: the
-- most specific classes are scanned first so a chest is recorded as a
-- chest, not as the generic accessible gimmick it also is.
local CLASSES = {
    { class = "RODTBoxBase",                kind = "chest" },
    { class = "RODChestBase",               kind = "chest_town" },
    { class = "RODSubQuestGimmickBase",     kind = "subquest_trinket" },
    { class = "RODSealedArkBase",           kind = "sealed_ark" },
    { class = "RODSealedBase",              kind = "seal" },
    { class = "RODArkBase",                 kind = "ark" },
    { class = "RODTipsGimmickBase",         kind = "lore_tip" },
    { class = "RODGiftPillar",              kind = "gift_pillar" },
    { class = "RODMapPinBase",              kind = "map_pin" },
    { class = "RODQuestTerminalBase",       kind = "quest_terminal" },
    { class = "RODActivatableTerminalBase", kind = "terminal" },
    { class = "RODDungeonGuide",            kind = "dungeon_guide" },
    { class = "RODSignPost",                kind = "signpost" },
    { class = "RODGateDoorBase",            kind = "gate_door" },
    { class = "RODWallDoor",                kind = "wall_door" },
    { class = "RODBarrierBase",             kind = "barrier" },
    { class = "RODBreakableGimmickBase",    kind = "breakable" },
    { class = "RODSequenceCtrlGimmickBase", kind = "sequence_ctrl" },
    -- Generic base LAST: anything not matched above (the town Smithy and
    -- Item Seller among them) still gets captured, tagged honestly as
    -- "accessible" rather than mislabelled as something specific.
    { class = "RODAccessibleGimmickBase",   kind = "accessible" },
    { class = "RODInteractiveGimmickBase",  kind = "interactive" },
}

local found = {}      -- [key] = record
local seenObjects = {} -- guards against re-recording the same actor
local scans = 0
local skippedZero = 0  -- actors at (0,0,0): not yet placed, retried next scan

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

-- The actor's full name looks like:
--   BP_TBox_C /Game/ROD/Maps/Main/WL01/WorldComposition/LV_WL01_x05y04.LV_WL01_x05y04:PersistentLevel.BP_TBox_C_3
-- The level package is what we want -- it IS the chunk.
local function chunkOf(fullName)
    if not fullName then return nil end
    local pkg = string.match(fullName, "([^%s]+)%.[^%s:]+:PersistentLevel")
    if pkg then
        return string.match(pkg, "([^/]+)$") or pkg
    end
    return nil
end

local function currentQuestId()
    local ok, qid = pcall(function()
        local qm = FindFirstOf("RODQuestManager")
        if qm and qm:IsValid() then return qm:GetQuestID() end
        return nil
    end)
    if ok and qid and qid ~= 0 then return qid end
    return nil
end

local function playerPos()
    local ok, p = pcall(function()
        local pawn = FindFirstOf("RODPlayerCharacter") or FindFirstOf("RODCharacterBase")
        if pawn and pawn:IsValid() then
            local l = pawn:K2_GetActorLocation()
            return { x = l.X, y = l.Y, z = l.Z }
        end
        return nil
    end)
    if ok then return p end
    return nil
end

-- Each gimmick type names itself differently. Try the fields the SDK
-- actually declares, in order, and fall back to the actor's own name --
-- never invent an id.
local function idOf(actor, kind)
    local id, subQuestId

    pcall(function()
        if actor.LocatorName then
            local s = actor.LocatorName:ToString()
            if s and s ~= "" and s ~= "None" then id = s end
        end
    end)
    if not id then
        pcall(function()
            if actor.ID then
                -- ID is FName on most, int32 on RODTipsGimmickBase.
                if type(actor.ID) == "number" then
                    if actor.ID ~= 0 then id = tostring(actor.ID) end
                else
                    local s = actor.ID:ToString()
                    if s and s ~= "" and s ~= "None" then id = s end
                end
            end
        end)
    end
    pcall(function()
        if actor.SubQuestID then
            local s = actor.SubQuestID:ToString()
            if s and s ~= "" and s ~= "None" then subQuestId = s end
        end
    end)
    if not id then
        pcall(function() id = actor:GetFName():ToString() end)
    end
    return id, subQuestId
end

local function scan()
    scans = scans + 1
    local qid = currentQuestId()
    local ppos = playerPos()
    local added = 0

    for _, entry in ipairs(CLASSES) do
        local ok, actors = pcall(function() return FindAllOf(entry.class) end)
        if ok and actors then
            for _, a in ipairs(actors) do
                pcall(function()
                    if not a:IsValid() then return end
                    local full = a:GetFullName()

                    -- Class Default Objects are not placed actors. UE4SS
                    -- returns them from FindAllOf, and they sit at the
                    -- world origin -- which is how the first sweep
                    -- produced 22 gimmicks at exactly (0,0,0), 20 of them
                    -- in towns. Skip them outright.
                    if string.find(full, "Default__", 1, true) then return end

                    local id, subQuestId = idOf(a, entry.kind)
                    local loc = a:K2_GetActorLocation()
                    local chunk = chunkOf(full)
                    local key = entry.kind .. "|" .. tostring(id)

                    -- A real gimmick is never at exactly (0,0,0): that's
                    -- an actor whose level is loaded but whose transform
                    -- hasn't been applied yet (town gimmicks do this
                    -- while you're out in the field). Do NOT record it,
                    -- and do NOT mark it seen -- so the next scan tries
                    -- again, and it's captured properly once you walk
                    -- into the town.
                    if loc.X == 0 and loc.Y == 0 and loc.Z == 0 then
                        skippedZero = skippedZero + 1
                        return
                    end

                    if seenObjects[full] then return end
                    seenObjects[full] = true

                    if not found[key] then
                        found[key] = {
                            kind = entry.kind,
                            class = entry.class,
                            id = id,
                            subQuestId = subQuestId,
                            x = loc.X, y = loc.Y, z = loc.Z,
                            chunk = chunk,
                            questId = qid,
                            playerX = ppos and ppos.x or nil,
                            playerY = ppos and ppos.y or nil,
                            playerZ = ppos and ppos.z or nil,
                        }
                        added = added + 1
                        if CONFIG.VERBOSE then
                            log(string.format("%s %s @ %s", entry.kind, tostring(id), tostring(chunk)))
                        end
                    end
                end)
            end
        end
    end

    local total, byKind = 0, {}
    for _, r in pairs(found) do
        total = total + 1
        byKind[r.kind] = (byKind[r.kind] or 0) + 1
    end

    if added > 0 then
        local parts = {}
        for k, n in pairs(byKind) do parts[#parts + 1] = string.format("%s:%d", k, n) end
        table.sort(parts)
        log(string.format("+%d new (%d total) [%s]%s", added, total, table.concat(parts, " "),
            qid and (" quest " .. tostring(qid)) or ""))
    end
    if skippedZero > 0 and scans % 5 == 0 then
        log(string.format("(%d actor(s) still unplaced at 0,0,0 -- walk into their area/town and they'll be captured)", skippedZero))
    end
    skippedZero = 0

    if CONFIG.AUTOSAVE_EVERY_SCANS > 0 and scans % CONFIG.AUTOSAVE_EVERY_SCANS == 0 and total > 0 then
        save()
    end
end

local function esc(s)
    if s == nil then return "null" end
    return '"' .. string.gsub(tostring(s), '"', '\\"') .. '"'
end

function save()
    local parts, total = {}, 0
    for _, r in pairs(found) do
        total = total + 1
        parts[#parts + 1] = string.format(
            '  {"kind":%s,"class":%s,"id":%s,"subQuestId":%s,"x":%.3f,"y":%.3f,"z":%.3f,"chunk":%s,"questId":%s}',
            esc(r.kind), esc(r.class), esc(r.id), esc(r.subQuestId),
            r.x, r.y, r.z, esc(r.chunk), r.questId and tostring(r.questId) or "null")
    end
    local json = '{\n "capturedBy": ' .. esc(NAME) .. ',\n "count": ' .. total ..
                 ',\n "gimmicks": [\n' .. table.concat(parts, ",\n") .. '\n ]\n}\n'

    local f, err = io.open(CONFIG.OUTPUT_FILE, "w")
    if not f then
        log("could not open " .. CONFIG.OUTPUT_FILE .. ": " .. tostring(err))
        return
    end
    f:write(json)
    f:close()
    log(string.format("wrote %d gimmicks -> %s (upload on the Build Dashboard; uploads MERGE)",
        total, CONFIG.OUTPUT_FILE))
end

RegisterKeyBind(CONFIG.DUMP_KEY, function() save() end)

LoopAsync(CONFIG.SCAN_INTERVAL_MS, function()
    scan()
    return false
end)

log(string.format("loaded — scanning every %ds. Gimmicks are captured as their CELL streams in, so walk the ground; a named area spans several cells.",
    CONFIG.SCAN_INTERVAL_MS // 1000))
