-- {MOD} — grant player EXP on a hotkey
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- REPLACES the level-swap mod, which didn't work. Your suggestion was the
-- right one: the Col grant worked because it used the game's OWN grant
-- function, while the level swap poked URODUserInfo::Level directly -- a
-- display/state field the game recomputes from EXP, so writing it changed
-- nothing that stuck.
--
-- The game ships its own EXP grant, and this uses it:
--     ARODInGamePlayerController::DebugAddHeroExp(int32)
--     ARODInGamePlayerController::ServerDebugAddHeroExp(int32)
--
-- Server-authoritative games apply changes on the server and replicate
-- back, so the Server* variant is called first and the local one used as a
-- fallback. Level-ups, stat points and the UI all follow naturally,
-- because this is the path the game itself uses when you kill something.

local CONFIG = {
    EXP_KEY    = Key.{EXP_KEY},
    EXP_AMOUNT = {EXP_AMOUNT},
}

local NAME = "{MOD}"
-- UE4SS key binds fire on UE4SS's OWN thread, not the game thread. UObject
-- work from the wrong thread silently does nothing -- which is why the EXP
-- grant, the town-chest fill and the enemy kill all "ran" and changed
-- nothing. Every working community mod for this game (DropRateScaling,
-- Norescue, AutoRipost) wraps its object work in ExecuteInGameThread; so do
-- these now.

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

-- WHAT THE PROBE CHANGED:
--   * DebugAddHeroExp / ServerDebugAddHeroExp are CALLABLE but INERT --
--     debug stubs in the shipping build. pcall succeeds, nothing moves.
--   * FindFirstOf("RODUserInfo") finds nothing, because UserInfo isn't a
--     free-floating object: it's held by URODSaveLoadSubsystem.RODUserInfo.
--     You reach it through its OWNER.
-- So this now writes Experience (and optionally Level) on the real UserInfo,
-- and READS IT BACK to prove it stuck. It also tries the game's own debug
-- functions first, because if they ever DO work they're the better path.

local function userInfo()
    local ui
    pcall(function()
        local subs = FindAllOf("RODSaveLoadSubsystem")
        for _, s in ipairs(subs or {}) do
            if s:IsValid() and s.RODUserInfo and s.RODUserInfo:IsValid() then
                ui = s.RODUserInfo
                return
            end
        end
    end)
    if not ui then
        pcall(function()
            local d = FindFirstOf("RODUserInfo")
            if d and d:IsValid() then ui = d end
        end)
    end
    return ui
end

RegisterKeyBind(CONFIG.EXP_KEY, function()
    ExecuteInGameThread(function()
        -- 1. The game's own verb, in case it starts working.
        local pc = FindFirstOf("RODInGamePlayerController")
        if pc and pc:IsValid() then
            pcall(function() pc:ServerDebugAddHeroExp(CONFIG.EXP_AMOUNT) end)
            pcall(function() pc:DebugAddHeroExp(CONFIG.EXP_AMOUNT) end)
        end

        -- 2. The one that actually holds the number.
        local ui = userInfo()
        if not ui then
            log("URODUserInfo not reachable (not in a save yet?) — nothing to add EXP to")
            return
        end

        local before = tonumber(ui.Experience)
        if not before then
            log("UserInfo.Experience isn't readable as a number — run ProgressionLogger and send Progression.txt")
            return
        end

        local target = before + CONFIG.EXP_AMOUNT
        pcall(function() ui.Experience = target end)

        local after = tonumber(ui.Experience)
        if after and after >= target then
            log(string.format("+%d EXP (%d -> %d)", CONFIG.EXP_AMOUNT, before, after))
            log("NOTE: the game may only recompute your LEVEL on the next level-up event "
                .. "(kill something, or open the menu). If the level never moves, the EXP-by-kill "
                .. "route (KillNearby) is the honest fix.")
        else
            log(string.format("write did NOT stick (%d -> %s). The game is recomputing Experience; "
                .. "use KillNearby instead.", before, tostring(after)))
        end
    end)
end)

log(string.format("loaded — press the hotkey for +%d EXP", CONFIG.EXP_AMOUNT))
