-- {MOD} — grant Col on a hotkey
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Standalone, because you said this one worked and bundling it with the
-- others made it unusable when they didn't.
--
-- Uses ARODPlayerState::AddCol(int32) -- the game's own grant path, the
-- same one a real pickup runs, so the balance, the UI and the save all
-- agree.

local CONFIG = {
    COL_KEY    = Key.{COL_KEY},
    COL_AMOUNT = {COL_AMOUNT},
}

local NAME = "{MOD}"
-- UE4SS key binds fire on UE4SS's OWN thread, not the game thread. UObject
-- work from the wrong thread silently does nothing -- which is why the EXP
-- grant, the town-chest fill and the enemy kill all "ran" and changed
-- nothing. Every working community mod for this game (DropRateScaling,
-- Norescue, AutoRipost) wraps its object work in ExecuteInGameThread; so do
-- these now.

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function playerState()
    local ok, ps = pcall(function()
        local pc = FindFirstOf("RODInGamePlayerController")
        if pc and pc:IsValid() and pc.PlayerState and pc.PlayerState:IsValid() then
            return pc.PlayerState
        end
        return FindFirstOf("RODPlayerState")
    end)
    if ok and ps and ps:IsValid() then return ps end
    return nil
end

RegisterKeyBind(CONFIG.COL_KEY, function()
    ExecuteInGameThread(function()
        local ps = playerState()
        if not ps then log("no PlayerState — are you in-game?"); return end
        local before = ps.Col
        local ok = pcall(function() ps:AddCol(CONFIG.COL_AMOUNT) end)
        if not ok then log("AddCol failed"); return end
        log(string.format("+%d Col (%s -> %s)", CONFIG.COL_AMOUNT, tostring(before), tostring(ps.Col)))
    end)
end)

log(string.format("loaded — press the hotkey for +%d Col", CONFIG.COL_AMOUNT))
