-- {MOD} — hotkey utilities: Col, level swap, teleport menu
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
--   F8  give Col (default 9000)
--   F7  set level to 200  /  press again to restore your real level
--   F9  open the fast-travel map (the one Safe Area terminals show)
--
-- All three are grounded in the game's own SDK, not guesswork:
--   ARODPlayerState::AddCol(int32)             -- the game's own Col grant
--   ARODPlayerState::Col                       -- current balance (int32)
--   URODUserInfo::Level                        -- the player's level
--   ARODInGamePlayerController::OpenDirectingMapMenu()
--                                              -- the terminal's warp map
--
-- ON THE COL "DROP": the request was to spawn a 9000-Col pickup at the
-- player's feet. The game HAS a native way to grant Col -- AddCol() on the
-- PlayerState -- and that's what this uses. It's the same code path the
-- game runs when you actually collect a drop, so the balance, the UI and
-- any save logic all update correctly. Spawning a physical pickup actor
-- would look prettier and could desync the total; this is the honest
-- version of the same wish. Say the word if you want the literal actor.
--
-- ON THE LEVEL SWAP: your real level is saved to disk BEFORE the first
-- override, keyed by save slot, so it survives a crash or a forgotten
-- restore. The slot is read from the game where possible; if it can't be
-- determined the mod refuses to overwrite a stored value rather than risk
-- filing your level under the wrong slot.

local CONFIG = {
    COL_KEY    = Key.{COL_KEY},
    COL_AMOUNT = {COL_AMOUNT},

    LEVEL_KEY      = Key.{LEVEL_KEY},
    LEVEL_OVERRIDE = {LEVEL_OVERRIDE},

    TELEPORT_KEY = Key.{TELEPORT_KEY},

    -- Where the real levels are remembered, next to the UE4SS dll.
    LEVEL_STORE = "PlayerLevels.json",
}

local NAME = "{MOD}"
local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

-- ---------------------------------------------------------------
-- Tiny JSON read/write. The store is a flat { "slot": level } map, so a
-- full JSON library isn't worth vendoring into a UE4SS mod.
-- ---------------------------------------------------------------
local function loadLevels()
    local f = io.open(CONFIG.LEVEL_STORE, "r")
    if not f then return {} end
    local text = f:read("*a")
    f:close()
    local out = {}
    for slot, lvl in string.gmatch(text or "", '"([^"]+)"%s*:%s*(%d+)') do
        out[slot] = tonumber(lvl)
    end
    return out
end

local function saveLevels(levels)
    local parts = {}
    for slot, lvl in pairs(levels) do
        parts[#parts + 1] = string.format('  "%s": %d', slot, lvl)
    end
    local f, err = io.open(CONFIG.LEVEL_STORE, "w")
    if not f then
        log("could not write " .. CONFIG.LEVEL_STORE .. ": " .. tostring(err))
        return false
    end
    f:write("{\n" .. table.concat(parts, ",\n") .. "\n}\n")
    f:close()
    return true
end

-- ---------------------------------------------------------------
local function playerState()
    local ok, ps = pcall(function()
        local pc = FindFirstOf("RODInGamePlayerController")
        if pc and pc:IsValid() and pc.PlayerState and pc.PlayerState:IsValid() then
            return pc.PlayerState
        end
        return FindFirstOf("RODPlayerState")
    end)
    if ok and ps and ps:IsValid() then return ps end
    return nil
end

local function userInfo()
    local ok, ui = pcall(function() return FindFirstOf("RODUserInfo") end)
    if ok and ui and ui:IsValid() then return ui end
    return nil
end

-- The game has 3 save slots. Try to learn which one is loaded; if we
-- can't, say so rather than guessing -- filing your level under the wrong
-- slot is how you'd lose it.
local function saveSlot()
    local slot
    pcall(function()
        local gi = FindFirstOf("RODGameInstance")
        if not gi or not gi:IsValid() then return end
        for _, field in ipairs({ "CurrentSaveSlot", "SaveSlotIndex", "SelectedSlotIndex", "SlotIndex" }) do
            local v = gi[field]
            if type(v) == "number" then slot = v; return end
        end
    end)
    return slot
end

-- ---------------------------------------------------------------
-- F8 — Col
-- ---------------------------------------------------------------
RegisterKeyBind(CONFIG.COL_KEY, function()
    local ps = playerState()
    if not ps then log("no PlayerState — are you in-game?"); return end
    local before = ps.Col
    local ok = pcall(function() ps:AddCol(CONFIG.COL_AMOUNT) end)
    if not ok then log("AddCol failed"); return end
    log(string.format("+%d Col (%s -> %s)", CONFIG.COL_AMOUNT, tostring(before), tostring(ps.Col)))
end)

-- ---------------------------------------------------------------
-- F7 — level override / restore
-- ---------------------------------------------------------------
RegisterKeyBind(CONFIG.LEVEL_KEY, function()
    local ui = userInfo()
    if not ui then log("no UserInfo — are you in-game?"); return end

    local current = ui.Level
    local slot = saveSlot()
    local slotKey = slot and ("slot" .. tostring(slot)) or nil
    local levels = loadLevels()

    if current == CONFIG.LEVEL_OVERRIDE then
        -- Restore.
        local real = slotKey and levels[slotKey] or levels["unknown"]
        if not real then
            log(string.format("level is %d but no saved real level to restore — leaving it alone",
                CONFIG.LEVEL_OVERRIDE))
            return
        end
        ui.Level = real
        log(string.format("level restored to %d (from %s)", real, slotKey or "unknown slot"))
        return
    end

    -- Override. Remember the real level FIRST, and only overwrite an
    -- existing record if we actually know the slot.
    local key = slotKey or "unknown"
    if slotKey or not levels[key] then
        levels[key] = current
        saveLevels(levels)
    end
    ui.Level = CONFIG.LEVEL_OVERRIDE
    log(string.format("level %d -> %d (real level saved under %s%s)",
        current, CONFIG.LEVEL_OVERRIDE, key,
        slotKey and "" or " — could NOT read the save slot, so this is filed as 'unknown'"))
end)

-- ---------------------------------------------------------------
-- F9 — fast-travel map (the Safe Area terminal menu)
-- ---------------------------------------------------------------
RegisterKeyBind(CONFIG.TELEPORT_KEY, function()
    local pc = FindFirstOf("RODInGamePlayerController")
    if not pc or not pc:IsValid() then log("no player controller"); return end
    local ok = pcall(function() pc:OpenDirectingMapMenu() end)
    if ok then
        log("opened the fast-travel map")
    else
        log("OpenDirectingMapMenu failed — the game may block it here (in combat, a cutscene, or a dungeon)")
    end
end)

log("loaded — F8 Col, F7 level swap, F9 fast-travel map (see the mod's config for keys)")
