-- {MOD} — raise inventory grid slots
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- HONEST STATUS, READ THIS FIRST: the game's JSON exports contain NO
-- inventory-capacity field (searched exhaustively). The game's Dumper-7
-- SDK has exactly one candidate: URODGridListWidgetBase, with
--     int32 GridColumn;  int32 GridRow;  int32 GridItemMax;  int32 GridItemMin;
-- That is a UI GRID capacity, which is very likely what you see as
-- "15 slots" (e.g. 3 x 5). What is NOT confirmed is whether it also
-- gates possession -- the game may page instead. So this mod does two
-- things:
--   1. DUMP mode (default): logs the live grid widgets and their real
--      values, so you can SEE what the game actually uses before
--      changing anything.
--   2. SET mode: overrides them.
-- Run DUMP first, read the log, then set SET_ENABLED = true. That order
-- is the difference between a mod that works and a mod that quietly
-- does nothing.

local CONFIG = {
    DUMP_ON_LOAD = true,

    SET_ENABLED   = {SET_ENABLED},
    NEW_GRID_ROW  = {NEW_GRID_ROW},
    NEW_ITEM_MAX  = {NEW_ITEM_MAX},

    -- Only touch widgets whose name contains this (keeps the change to
    -- item lists rather than every grid in the UI). "" = all grids.
    RESTRICT_TO_NAME = "{RESTRICT_TO_NAME}",

    POLL_MS = 3000,
}

local NAME = "{MOD}"
local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function eachGrid(fn)
    local ok, grids = pcall(function() return FindAllOf("RODGridListWidgetBase") end)
    if not ok or not grids then return 0 end
    local n = 0
    for _, g in ipairs(grids) do
        if g:IsValid() then
            local name = g:GetFullName()
            if CONFIG.RESTRICT_TO_NAME == "" or string.find(name, CONFIG.RESTRICT_TO_NAME) then
                pcall(fn, g, name)
                n = n + 1
            end
        end
    end
    return n
end

local function dump()
    local n = eachGrid(function(g, name)
        log(string.format("grid %s | GridColumn=%s GridRow=%s GridItemMax=%s GridItemMin=%s",
            name, tostring(g.GridColumn), tostring(g.GridRow),
            tostring(g.GridItemMax), tostring(g.GridItemMin)))
    end)
    log(string.format("%d grid widget(s) live right now (open your inventory, then check again)", n))
end

local function apply()
    local n = eachGrid(function(g)
        if CONFIG.NEW_GRID_ROW > 0 then g.GridRow = CONFIG.NEW_GRID_ROW end
        if CONFIG.NEW_ITEM_MAX > 0 then g.GridItemMax = CONFIG.NEW_ITEM_MAX end
    end)
    if n > 0 then log(string.format("applied to %d grid(s): GridRow=%d GridItemMax=%d", n, CONFIG.NEW_GRID_ROW, CONFIG.NEW_ITEM_MAX)) end
end

if CONFIG.DUMP_ON_LOAD then
    LoopAsync(CONFIG.POLL_MS, function() dump(); return true end)  -- once
end

if CONFIG.SET_ENABLED then
    -- Widgets are constructed when menus open, so re-apply on a poll
    -- rather than once at load.
    LoopAsync(CONFIG.POLL_MS, function() apply(); return false end)
end

log("loaded — " .. (CONFIG.SET_ENABLED and "SET mode" or "DUMP mode (read the log, then enable SET)"))
