-- {MOD} — kill (or weaken) nearby enemies on a hotkey
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- YOUR IDEA, and it may fix the EXP mod too. You asked: "could we mimic
-- the death of a basic enemy to award the experience?" The game has
-- exactly that function, on the enemy itself:
--
--     ARODEnemyCharacter::KillingBlow(ACharacter* InstigatorCharacter,
--                                     FGameplayTag InstigatingSkillTag)
--
-- That's the game's OWN death path -- the one it runs when you land the
-- final hit. If it works, the kill, the EXP, the weapon proficiency, the
-- drops and the quest counters all follow for free, because we're not
-- awarding anything: we're telling the game you killed something and
-- letting it do what it always does.
--
-- That's the same principle that made the Col mod work (AddCol is the
-- game's own verb) and the level mod fail (it poked a number the game
-- recomputes). Prefer the game's verbs over its nouns.
--
-- WHAT THE PROBE TAUGHT US (2026-07-12):
--   * Enemy attribute writes WORK. FindAllOf("RODDefensiveAttributeSet")
--     returns 21 sets, their Outer IS the enemy actor, and
--     Health.CurrentValue reads (1280.0) and writes cleanly.
--   * KillingBlow is CALLABLE but did nothing when called. Almost certainly
--     the FGameplayTag argument: passing {} is not a valid tag, and the
--     game's death path likely bails on it. Calling a function successfully
--     is not the same as it doing something.
-- So "weaken" is now the DEFAULT, because it's built on the one thing we
-- have actually proven works. "kill" is kept, because if the tag issue is
-- solved it's still the better answer (real death path = real rewards).
--
-- MODE matters, so read this:
--   "kill"    -- call KillingBlow with YOU as the instigator. The full
--               death path. This is the one that should award EXP.
--   "weaken"  -- set each enemy's Health to WEAKEN_TO (default 1) and
--               leave the killing to you. Safer: if KillingBlow turns out
--               to misbehave (bosses with multi-stage HP bars, scripted
--               fights, quest enemies that must die a specific way), this
--               never fights the game's own logic.
--
-- Bosses are EXCLUDED by default. A boss killed outside its scripted fight
-- can leave a quest in a state the game can't resolve -- and a stuck save
-- is a much worse outcome than a slow boss fight. Turn it on if you want,
-- but that's the risk you're taking.

local CONFIG = {
    KILL_KEY = Key.{KILL_KEY},
    -- "kill" or "weaken"
    MODE = "{MODE}",   -- "weaken" is proven; "kill" is not (see above)
    WEAKEN_TO = {WEAKEN_TO},
    -- Radius in cm. 3000 = 30m.
    RADIUS = {RADIUS},
    INCLUDE_BOSSES = {INCLUDE_BOSSES},
}

local NAME = "{MOD}"
-- UE4SS key binds fire on UE4SS's OWN thread, not the game thread. UObject
-- work from the wrong thread silently does nothing -- which is why the EXP
-- grant, the town-chest fill and the enemy kill all "ran" and changed
-- nothing. Every working community mod for this game (DropRateScaling,
-- Norescue, AutoRipost) wraps its object work in ExecuteInGameThread; so do
-- these now.

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

-- The hero's attribute sets are found by owner, never by blanket
-- FindAllOf -- but for ENEMIES it's the reverse problem: we want everyone
-- EXCEPT the hero, and we must be sure we never write to the hero's own
-- Health by mistake.
local function heroActor()
    local h = FindFirstOf("RODHeroCharacter")
    if h and h:IsValid() then return h end
    return nil
end

local function setOwnedBy(set, actorFullName)
    local match = false
    pcall(function()
        local o = set:GetOuter()
        if not o or not o:IsValid() then return end
        local owner = o
        if o.OwnerActor and o.OwnerActor:IsValid() then owner = o.OwnerActor end
        if owner:GetFullName() == actorFullName then match = true end
    end)
    return match
end

local function defensiveSetOf(actor)
    local ok, sets = pcall(function() return FindAllOf("RODDefensiveAttributeSet") end)
    if not ok or not sets then return nil end
    local full = actor:GetFullName()
    for _, s in ipairs(sets) do
        local valid = false
        pcall(function() valid = s:IsValid() end)
        if valid and setOwnedBy(s, full) then return s end
    end
    return nil
end

local function isBoss(enemy)
    local boss = false
    pcall(function()
        if enemy.bIsBoss ~= nil then boss = enemy.bIsBoss
        elseif enemy.IsBoss ~= nil then boss = enemy.IsBoss
        elseif enemy.GetCurrentHPBarNum and enemy:GetCurrentHPBarNum() > 1 then
            -- Multi-stage HP bars are a boss tell when no flag is exposed.
            boss = true
        end
    end)
    return boss
end

RegisterKeyBind(CONFIG.KILL_KEY, function()
    ExecuteInGameThread(function()
        local hero = heroActor()
        if not hero then log("no hero — are you in-game?"); return end
        local heroFull = hero:GetFullName()
        local here = hero:K2_GetActorLocation()

        local ok, enemies = pcall(function() return FindAllOf("RODEnemyCharacter") end)
        if not ok or not enemies then log("no enemies loaded"); return end

        local hit, skipped, bosses, failed = 0, 0, 0, 0

        for _, e in ipairs(enemies) do
            pcall(function()
                if not e:IsValid() then return end
                -- Never, ever touch the player.
                if e:GetFullName() == heroFull then return end

                local loc = e:K2_GetActorLocation()
                -- (0,0,0) = not actually placed yet. Skip.
                if loc.X == 0 and loc.Y == 0 and loc.Z == 0 then return end

                local dx, dy, dz = loc.X - here.X, loc.Y - here.Y, loc.Z - here.Z
                local dist = math.sqrt(dx * dx + dy * dy + dz * dz)
                if dist > CONFIG.RADIUS then skipped = skipped + 1; return end

                if isBoss(e) and not CONFIG.INCLUDE_BOSSES then
                    bosses = bosses + 1
                    return
                end

                if CONFIG.MODE == "kill" then
                    -- The game's own death path, with YOU as the instigator --
                    -- which is what makes the rewards land.
                    local killed = pcall(function() e:KillingBlow(hero, {}) end)
                    if killed then
                        hit = hit + 1
                    else
                        failed = failed + 1
                    end
                else
                    local def = defensiveSetOf(e)
                    if not def then failed = failed + 1; return end
                    local after
                    pcall(function()
                        def.Health.BaseValue = CONFIG.WEAKEN_TO
                        def.Health.CurrentValue = CONFIG.WEAKEN_TO
                        after = def.Health.CurrentValue
                    end)
                    -- VERIFY. A write that reports success but doesn't stick is
                    -- exactly the failure mode that wasted rounds of testing on
                    -- the stat mods -- so read it back rather than assume.
                    if after and math.abs(after - CONFIG.WEAKEN_TO) < 0.01 then
                        hit = hit + 1
                    else
                        failed = failed + 1
                    end
                end
            end)
        end

        log(string.format("%s: %d enemy(s) within %.0fm%s%s%s",
            CONFIG.MODE == "kill" and "killed" or ("set to " .. CONFIG.WEAKEN_TO .. " HP"),
            hit, CONFIG.RADIUS / 100,
            bosses > 0 and string.format("; %d boss(es) skipped", bosses) or "",
            failed > 0 and string.format("; %d failed", failed) or "",
            skipped > 0 and string.format("; %d out of range", skipped) or ""))

        if hit == 0 and failed > 0 then
            log("nothing worked — run the DebugProbe mod; it reports whether KillingBlow is callable at all")
        end
    end)
end)

log(string.format("loaded — %s mode, %.0fm radius, bosses %s",
    CONFIG.MODE, CONFIG.RADIUS / 100, CONFIG.INCLUDE_BOSSES and "INCLUDED" or "skipped"))
