-- {MOD} — stop the game rescuing you when you fall
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- The game "rescues" a player who falls below a death plane by teleporting
-- them back — which is exactly what you do NOT want while mapping, since it
-- yanks you out of wherever you were exploring.
--
-- This raises the death-landing height so the fall-rescue never triggers,
-- and re-applies it after a respawn (the game resets it), by hooking the
-- engine's own restart:
--     /Script/Engine.PlayerController:ClientRestart
--
-- Being straight about the trade: with the rescue disabled, a fall into
-- genuine void geometry has no safety net, so keep a save. That's the point
-- of the mod, but it's still worth saying out loud.

local CONFIG = {
    LANDING_HEIGHT = {LANDING_HEIGHT},
    REAPPLY_MS = {REAPPLY_MS},
    TOGGLE_KEY = Key.{TOGGLE_KEY},
    START_ENABLED = {START_ENABLED},
}

local NAME = "{MOD}"
local enabled = CONFIG.START_ENABLED
local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function apply(reason)
    if not enabled then return end
    ExecuteInGameThread(function()
        local hero = FindFirstOf("RODHeroCharacter")
        if not hero or not hero:IsValid() then return end
        local applied = false
        pcall(function()
            -- Try the fields the game exposes for the death plane. Anything
            -- that isn't a number is skipped: UE4SS returns a dummy UObject
            -- for a property that doesn't exist, so `~= nil` proves nothing.
            for _, field in ipairs({ "DeathLandingHeight", "FallDeathHeight", "DeadLandingHeight" }) do
                local v = hero[field]
                if type(v) == "number" then
                    hero[field] = CONFIG.LANDING_HEIGHT
                    applied = true
                end
            end
        end)
        if applied then
            log(string.format("fall-rescue disabled (%s)", reason))
        end
    end)
end

pcall(function()
    RegisterHook("/Script/Engine.PlayerController:ClientRestart", function()
        -- The game resets this on respawn, so re-apply after each one.
        ExecuteWithDelay(CONFIG.REAPPLY_MS, function() apply("after respawn") end)
    end)
end)

RegisterKeyBind(CONFIG.TOGGLE_KEY, function()
    enabled = not enabled
    log(enabled and "no-rescue ON" or "no-rescue OFF (the game's rescue is back)")
    if enabled then apply("toggled on") end
end)

ExecuteWithDelay(CONFIG.REAPPLY_MS, function() apply("startup") end)
log("loaded")
