-- {MOD} — player movement speed multiplier
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Default 4x, as asked. Configurable below.
--
-- HOW THIS WORKS, and why it re-applies on a loop:
-- Movement speed comes from the CharacterMovementComponent's MaxWalkSpeed.
-- The game rewrites that value whenever your state changes (sprinting,
-- combat stance, being staggered, mounting, cutscenes...), so a one-shot
-- write gets silently reverted the first time you sprint. Instead this
-- samples the CURRENT speed, and if it isn't already our multiplied
-- value, multiplies it -- so the mod rides on top of whatever the game
-- just set rather than fighting it.
--
-- The BASE speed is captured once (the first non-multiplied value seen)
-- so the multiplier can never compound into a 4x-of-4x runaway.

local CONFIG = {
    MULTIPLIER = {MULTIPLIER},
    -- How often to re-assert. 100ms is responsive without being heavy;
    -- the whole check is one property read.
    INTERVAL_MS = {INTERVAL_MS},
    TOGGLE_KEY = Key.{TOGGLE_KEY},
    START_ENABLED = {START_ENABLED},
}

local NAME = "{MOD}"
-- ---------------------------------------------------------------------
-- WHY EVERY UOBJECT OPERATION BELOW IS WRAPPED IN ExecuteInGameThread:
--
-- UE4SS runs Lua callbacks (key binds, LoopAsync) on its OWN thread. The
-- game's objects live on the GAME thread. Touching a UObject from the wrong
-- thread doesn't error -- it just quietly does nothing, or worse. That is
-- exactly the failure we kept hitting: mods that installed cleanly, logged
-- happily, and changed nothing at all.
--
-- Confirmed by reading working community mods for this game (DropRateScaling,
-- AutoRipost, Norescue): every one of them wraps its object work in
-- ExecuteInGameThread. The mods that DID work here by accident (movement
-- speed) were writing a value the engine re-reads every frame anyway, which
-- masked the problem.
-- ---------------------------------------------------------------------

local enabled = CONFIG.START_ENABLED
local baseSpeeds = {}   -- [movement component full name] = original MaxWalkSpeed

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function playerMovement()
    local hero = FindFirstOf("RODHeroCharacter")
    if not hero or not hero:IsValid() then return nil end
    local mv = hero.CharacterMovement
    if not mv or not mv:IsValid() then return nil end
    return hero, mv
end

local function apply()
    ExecuteInGameThread(function()
        local ok = pcall(function()
            local hero, mv = playerMovement()
            if not mv then return end

            local key = mv:GetFullName()
            local current = mv.MaxWalkSpeed
            local target = (baseSpeeds[key] or current) * CONFIG.MULTIPLIER

            if not enabled then
                -- Restore exactly once, then leave the game alone.
                if baseSpeeds[key] and math.abs(current - baseSpeeds[key]) > 0.01 then
                    mv.MaxWalkSpeed = baseSpeeds[key]
                end
                return
            end

            -- Learn the base speed from any value that ISN'T our own output.
            -- This is what keeps 4x from becoming 16x when the game re-sets
            -- the speed and we multiply again.
            if math.abs(current - target) > 0.01 then
                if math.abs(current - (baseSpeeds[key] or -1)) > 0.01 then
                    baseSpeeds[key] = current
                    target = current * CONFIG.MULTIPLIER
                end
                mv.MaxWalkSpeed = target
            end
        end)
        if not ok then --[[ character not spawned yet; try again next tick ]] end
    end)
end

RegisterKeyBind(CONFIG.TOGGLE_KEY, function()
    enabled = not enabled
    log(enabled and string.format("speed x%.1f ON", CONFIG.MULTIPLIER) or "speed restored to normal")
end)

LoopAsync(CONFIG.INTERVAL_MS, function()
    apply()
    return false
end)

log(string.format("loaded — speed x%.1f %s (toggle with the hotkey)",
    CONFIG.MULTIPLIER, enabled and "ENABLED" or "disabled"))
