-- {MOD} — log player progression: EXP, level, weapon proficiency, stats, rank
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- THIS IS THE MOD THAT UNBLOCKS THE OTHERS.
--
-- The DebugProbe found that FindFirstOf("RODUserInfo") returns NOTHING at
-- runtime -- which is why the EXP mod and the level mod had nothing to write
-- to. But the SDK says URODUserInfo is where nearly all progression lives:
--
--     URODUserInfo : Level, Experience, GrowPoint, Col, TotalCol, Yell,
--                    WeaponExperienceData (TArray<FWeaponExperienceData>
--                        -- one {Level, Experience} PER WEAPON TYPE),
--                    AcquiredSwordSkills, ActivatedTerminalData,
--                    OpenedFixBoxIDs, ...
--
-- The reason it can't be found directly: it isn't a free-floating object.
-- It's held by a subsystem --
--     URODSaveLoadSubsystem : RODUserInfo, DefaultUserInfo
-- -- so you reach it through its OWNER, not by searching for it. That single
-- fact is what makes weapon-proficiency EXP reachable at all.
--
-- WHAT THIS LOGS
--   * Level / Experience / GrowPoint / Col / Yell
--   * WEAPON PROFICIENCY per weapon type: level + EXP for each entry in
--     WeaponExperienceData (the array index is the weapon type)
--   * Every Gameplay Ability System attribute the hero owns -- ATK, BaseATK,
--     CoefATK, BonusATK, DEF/Base/Coef/Bonus, Health, Stamina, Soul,
--     Strain, SuSPoint, CoSPoint... which is where the effects of VIT / END /
--     MND / STR / DEX / AGI / INT actually SHOW UP. Those seven letters
--     aren't attributes themselves; they're inputs the game turns into these
--     Base/Coef/Bonus values, so logging the outputs is how you learn the
--     mapping. Level up, press the key, diff the numbers.
--   * Anything whose property name contains "Rank" -- the Cardinal Rank
--     system that gates shop tiers and weapon upgrades. I could NOT find it
--     named in the SDK, so this hunts for it rather than pretending to know
--     where it lives. If it shows up, we'll know.
--
-- Writes Progression.txt (appends, with a timestamp) so you can press it
-- before and after a quest/level-up and diff the two.

local CONFIG = {
    LOG_KEY = Key.{LOG_KEY},
    -- Also log automatically every N ms (0 = only on the key).
    AUTO_MS = {AUTO_MS},
    OUTPUT_FILE = "Progression.txt",
}

local NAME = "{MOD}"
local lines = {}

local function out(m)
    print(string.format("[%s] %s\n", NAME, tostring(m)))
    lines[#lines + 1] = tostring(m)
end

local function num(v)
    -- UE4SS hands back a dummy UObject for a property that doesn't exist,
    -- so `~= nil` proves nothing. Only a real number counts.
    local n = tonumber(v)
    return n
end

-- URODUserInfo is reached through the subsystem that OWNS it, because it
-- cannot be found on its own.
local function userInfo()
    local ui
    pcall(function()
        local subs = FindAllOf("RODSaveLoadSubsystem")
        if subs then
            for _, s in ipairs(subs) do
                if s:IsValid() and s.RODUserInfo and s.RODUserInfo:IsValid() then
                    ui = s.RODUserInfo
                    return
                end
            end
        end
    end)
    -- Fall back to a direct search, in case a build exposes it.
    if not ui then
        pcall(function()
            local direct = FindFirstOf("RODUserInfo")
            if direct and direct:IsValid() then ui = direct end
        end)
    end
    return ui
end

local function logUserInfo()
    local ui = userInfo()
    if not ui then
        out("  URODUserInfo NOT reachable — not in a save yet?")
        return
    end
    out("  [UserInfo] found via " .. tostring(ui:GetFullName()))
    for _, f in ipairs({ "Level", "Experience", "GrowPoint", "Col", "TotalCol", "Yell", "TotalPlayTime" }) do
        local v = num(ui[f])
        out(string.format("    %-14s %s", f, v and tostring(v) or "(not a number — field absent)"))
    end

    -- WEAPON PROFICIENCY. One {Level, Experience} per weapon type.
    out("  [Weapon proficiency]")
    local n = 0
    pcall(function()
        local arr = ui.WeaponExperienceData
        -- A UE4SS TArray is a UObject, not a Lua table: `#arr` throws. Ask it
        -- for its length properly, and fall back to walking indices.
        local count
        pcall(function() count = arr:GetArrayNum() end)
        if not count then
            pcall(function() count = #arr end)
        end
        for i = 1, (count or 12) do
            local ok = pcall(function()
                local e = arr[i]
                local lv, xp = num(e.Level), num(e.Experience)
                if lv or xp then
                    n = n + 1
                    out(string.format("    weapon[%d]  level %-4s exp %s",
                        i, tostring(lv or "?"), tostring(xp or "?")))
                end
            end)
            if not ok and count then break end
        end
    end)
    if n == 0 then
        out("    (none readable — the TArray may need a different access pattern; tell the toolkit)")
    end

    -- CARDINAL RANK: not named anywhere in the SDK, so hunt for it.
    out("  [Rank hunt] any readable property with 'Rank' in the name:")
    local found = 0
    pcall(function()
        for _, f in ipairs({ "CardinalRank", "Rank", "PlayerRank", "ShopRank", "CurrentRank",
                            "CardinalLevel", "RankPoint", "RankLevel" }) do
            local v = num(ui[f])
            if v then
                found = found + 1
                out(string.format("    UserInfo.%-14s %s", f, tostring(v)))
            end
        end
    end)
    if found == 0 then
        out("    nothing on UserInfo. Rank may live on the PlayerState or a quest subsystem —")
        out("    run this again after a Cardinal Rank UP and diff the files; whatever moved is it.")
    end
end

local function logAttributes()
    local hero = FindFirstOf("RODHeroCharacter")
    if not hero or not hero:IsValid() then out("  no hero"); return end
    local heroFull = hero:GetFullName()

    -- VIT/END/MND/STR/DEX/AGI/INT are NOT attributes in this game -- they're
    -- inputs the game converts into the Base/Coef/Bonus values below. Logging
    -- these before and after a stat point is how you learn which letter feeds
    -- which number.
    local SETS = {
        ["RODDefensiveAttributeSet"] = { "Health", "MaxHealth", "Def", "BaseDEF", "CoefDEF", "BonusDEF", "Barricade", "MaxBarricade" },
        ["RODOffensiveAttributeSet"] = { "ATK", "BaseATK", "CoefATK", "BonusATK", "Damage" },
        ["RODAvatarAttributeSet"]    = { "Stamina", "MaxStamina", "Soul", "MaxSoul", "MaxSpeed", "MinSpeed", "Revive", "MaxRevive" },
        ["RODHeroAttributeSet"]      = { "Strain", "SuSPoint", "MaxSuSPoint", "CoSPoint", "MaxCoSPoint", "EnhPouch" },
    }

    for cls, fields in pairs(SETS) do
        local set
        pcall(function()
            local all = FindAllOf(cls)
            if not all then return end
            for _, s in ipairs(all) do
                local mine = false
                pcall(function()
                    local o = s:GetOuter()
                    -- An AttributeSet's Outer IS the owning actor (probe-confirmed).
                    mine = o and o:IsValid() and o:GetFullName() == heroFull
                end)
                if mine then set = s; return end
            end
        end)
        if not set then
            out(string.format("  [%s] not owned by the hero / not found", cls))
        else
            out(string.format("  [%s]", cls))
            for _, f in ipairs(fields) do
                local cur, base
                pcall(function()
                    cur = tonumber(set[f].CurrentValue)
                    base = tonumber(set[f].BaseValue)
                end)
                if cur then
                    out(string.format("    %-14s current %-10.2f base %s", f, cur,
                        base and string.format("%.2f", base) or "?"))
                end
            end
        end
    end

    -- Plain floats that aren't GAS attributes.
    pcall(function()
        local av = nil
        local all = FindAllOf("RODAvatarAttributeSet")
        for _, s in ipairs(all or {}) do
            local o = s:GetOuter()
            if o and o:IsValid() and o:GetFullName() == heroFull then av = s end
        end
        if av then
            local atk = tonumber(av.EnhAtkSpeed)
            if atk then out(string.format("    %-14s %.3f  (plain float, not a GAS attribute)", "EnhAtkSpeed", atk)) end
        end
    end)
end

local function snapshot(reason)
    ExecuteInGameThread(function()
        lines = {}
        out("================ PROGRESSION (" .. tostring(reason) .. ") ================")
        logUserInfo()
        out("")
        logAttributes()
        out("=========================================================")

        local f = io.open(CONFIG.OUTPUT_FILE, "a")
        if f then
            f:write(os.date("%Y-%m-%d %H:%M:%S") .. "\n" .. table.concat(lines, "\n") .. "\n\n")
            f:close()
        end
    end)
end

RegisterKeyBind(CONFIG.LOG_KEY, function() snapshot("hotkey") end)

if CONFIG.AUTO_MS > 0 then
    LoopAsync(CONFIG.AUTO_MS, function() snapshot("auto"); return false end)
end

print(string.format("[%s] loaded — press the key to append a progression snapshot to %s. "
    .. "Take one BEFORE and one AFTER a level-up / rank-up and diff them.\n", NAME, CONFIG.OUTPUT_FILE))
