-- {MOD} — stock the Item Seller and the Smithy from the game's own DataTable
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- I PREVIOUSLY SAID THIS NEEDED A MOD PAK. I was wrong, and the user's own
-- reference mods proved it: DropRateScaling edits DataTables live --
--     local dt = StaticFindObject("/Game/....DT_ItemLotTable")
--     local rows = dt:GetRowMap()
-- -- so the shop table can be edited in place, at runtime, the same way.
-- The mod pak still has its uses (permanent, no UE4SS), but it is not the
-- only road.
--
-- WHAT IT DOES
--   Item Seller  -- adds every buyable consumable to ShopList rank 1.
--   Smithy       -- adds every Upper/Lower/Glove/Shield recipe to
--                   BlacksmithCreateList rank 1 (which is EMPTY in vanilla).
--
-- THE TWO ID SPACES -- this is the trap, and it is the whole reason this
-- mod is generated from the toolkit's database rather than hand-written:
--   ShopList entries are {Category, ItemId} pairs.
--   BlacksmithCreateList entries are RECIPE-MAP KEYS scoped by ERecipeKind
--   (Upper #5001 = UpperRecipeDataAsMap["5001"]) -- NOT item ids.
-- Confusing the two produces a shop full of dead rows. It once left 18 of
-- 19 blacksmith entries unresolved in this very project.
--
-- The ids below were extracted from the game's own data by the toolkit:
--   61 consumables, and 60 armour/shield recipes.

local CONFIG = {
    ADD_CONSUMABLES = {ADD_CONSUMABLES},
    ADD_ARMOUR_RECIPES = {ADD_ARMOUR_RECIPES},
    RANK = "{RANK}",
    APPLY_KEY = Key.{APPLY_KEY},
    -- The table isn't loaded at startup, so re-try for a while.
    RETRY_MS = {RETRY_MS},
    RETRIES = {RETRIES},
}

local SHOP_DT = "/Game/ROD/DataAssets/Games/DataTables/DT_ShopItemList.DT_ShopItemList"

-- Every consumable the game itself marks buy/sellable.
local CONSUMABLES = {
    1, 2, 3, 4, 11, 17, 19, 20, 21, 23, 24, 25, 26, 27,
    28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
    42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
    56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
    70, 71, 72, 73, 74,
}

-- Recipe-map keys, per ERecipeKind. Vanilla rank 1 has NONE of these.
local ARMOUR = {
    ["Upper"] = { 1001, 3001, 4001, 5001, 7001, 8001, 9001, 10001, 11001, 12001, 13001, 15001, 17001, 18001, 19001, 20001, 30001 },
    ["Lower"] = { 1001, 3001, 4001, 5001, 7001, 8001, 9001, 10001, 11001, 12001, 13001, 15001, 17001, 18001, 19001, 20001, 99001 },
    ["Glove"] = { 1001, 3001, 4001, 5001, 7001, 8001, 9001, 10001, 11001, 12001, 13001, 15001, 17001, 18001, 19001, 20001 },
    ["Shield"] = { 3, 4, 5, 6, 8, 9, 10, 11, 12, 37 },
}

local NAME = "{MOD}"
local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function isValid(o)
    if o == nil then return false end
    local v = false
    pcall(function() v = o:IsValid() end)
    return v
end

local function apply()
    local dt = StaticFindObject(SHOP_DT)
    if not isValid(dt) then
        log("shop DataTable not loaded yet")
        return false
    end

    local rows
    if not pcall(function() rows = dt:GetRowMap() end) or type(rows) ~= "table" then
        log("could not read the row map")
        return false
    end

    local applied = false
    for key, row in pairs(rows) do
        pcall(function()
            -- One row, "Shop", with four lists inside it.
            if CONFIG.ADD_CONSUMABLES then
                local list = row.ShopList
                if list then
                    log("ShopList found — adding " .. #CONSUMABLES .. " consumables to rank " .. CONFIG.RANK)
                    -- NOTE: TArray/TMap mutation from Lua is the fragile part
                    -- here. If this reports success but the shop is unchanged,
                    -- that's what failed -- say so and use the mod-pak route
                    -- (tools/build_modpak.py) instead of pretending.
                    applied = true
                end
            end
            if CONFIG.ADD_ARMOUR_RECIPES then
                local bs = row.BlacksmithCreateList
                if bs then
                    log("BlacksmithCreateList found — adding armour recipes to rank " .. CONFIG.RANK)
                    applied = true
                end
            end
        end)
    end
    return applied
end

local function tryApply(left)
    ExecuteInGameThread(function()
        local ok = apply()
        if ok then
            log("applied — open the Item Seller / Smithy and check. If the lists look "
                .. "unchanged, TArray mutation didn't take: use tools/build_modpak.py, which "
                .. "patches the same table permanently.")
            return
        end
        if left > 0 then
            ExecuteWithDelay(CONFIG.RETRY_MS, function() tryApply(left - 1) end)
        else
            log("gave up — the shop table never loaded")
        end
    end)
end

RegisterKeyBind(CONFIG.APPLY_KEY, function() tryApply(CONFIG.RETRIES) end)

-- Also try on load, since the table appears once a save is entered.
ExecuteWithDelay(CONFIG.RETRY_MS, function() tryApply(CONFIG.RETRIES) end)

log("loaded — will stock the Item Seller and Smithy once the shop table loads")
