-- {MOD} — raise item stack limits
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- WHY THIS EXISTS: every entry in the game's UseItemDataAsMap (the 61
-- consumables, healing potions included) ships with MaxStack = 5 --
-- verified in the real ItemDataAsset export, not assumed. The Heal map
-- is already 999, so it is left alone unless you enable it below.
--
-- This is a DATAASSET edit performed at runtime: it walks the live
-- URODItemDataAsset's TMap properties and rewrites MaxStack. Property
-- names come from the game's own Dumper-7 SDK (URODItemDataAsset ->
-- TMap<int32, FUseItemData> UseItemDataAsMap, with FUseItemData
-- inheriting MaxStack from FCommonItemDataTable), so they are the real
-- names, not guesses.
--
-- Every write is pcall-guarded: if a future patch renames a property,
-- this logs and keeps going instead of breaking your game.

local CONFIG = {
    NEW_MAX_STACK = {NEW_MAX_STACK},

    -- Which item maps to raise. Consumables are the point of this mod;
    -- the others are listed so you can opt in deliberately.
    MAPS = {
        UseItemDataAsMap      = true,   -- the 61 consumables (MaxStack 5 in vanilla)
        MaterialItemDataAsMap = {INCLUDE_MATERIALS},  -- materials (vanilla MaxStack -1 = unlimited)
        HealItemDataAsMap     = {INCLUDE_HEAL},  -- already 999 in vanilla
        KeyItemDataAsMap      = false,  -- key items: raising these is pointless and risky
    },

    DEBUG_LOGS = false,
}

local NAME = "{MOD}"
local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function applyStacks()
    local asset = FindFirstOf("RODItemDataAsset")
    if not asset or not asset:IsValid() then
        log("RODItemDataAsset not loaded yet — will retry")
        return false
    end

    local total = 0
    for mapName, enabled in pairs(CONFIG.MAPS) do
        if enabled then
            local ok, err = pcall(function()
                local map = asset[mapName]
                if not map then
                    log(string.format("property %s not found — skipping", mapName))
                    return
                end
                -- UE4SS exposes TMap with ForEach(key, value); the value
                -- is a wrapper, hence :get().
                map:ForEach(function(_, value)
                    local ok2 = pcall(function()
                        local entry = value:get()
                        if entry.MaxStack and entry.MaxStack > 0 and entry.MaxStack < CONFIG.NEW_MAX_STACK then
                            entry.MaxStack = CONFIG.NEW_MAX_STACK
                            total = total + 1
                        end
                    end)
                    if not ok2 and CONFIG.DEBUG_LOGS then log("entry write failed in " .. mapName) end
                end)
            end)
            if not ok then log(string.format("%s failed: %s", mapName, tostring(err))) end
        end
    end

    log(string.format("raised MaxStack to %d on %d item(s)", CONFIG.NEW_MAX_STACK, total))
    return true
end

-- The DataAsset isn't loaded at script time, so retry until it is
-- (then stop). 2s poll, gives up after ~2 minutes rather than looping
-- forever in the background.
local attempts = 0
LoopAsync(2000, function()
    attempts = attempts + 1
    if applyStacks() or attempts > 60 then return true end
    return false
end)
