-- {MOD} — teleport to the nearest Safe Area
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- REPLACES the "open the fast-travel map" mod, which was a bad idea and
-- your testing proved it: the menu opened with missing strings and COULD
-- NOT BE CLOSED -- you had to crash the game to escape it. That happened
-- because OpenDirectingMapMenu() was called out of context: the real menu
-- is opened BY a Safe Area terminal, which supplies the state the widget
-- needs and owns the close path. Calling the opener without the opener's
-- context gives you a half-built screen with no way out.
--
-- Rather than fake that context, this does the thing you actually wanted:
-- it finds the nearest Safe Area and moves you there. No menu, so nothing
-- can trap you.
--
-- HOW THE SAFE AREAS ARE FOUND: at runtime, via the game's own terminal
-- actors (ARODActivatableTerminalBase), whose ids the toolkit already
-- knows -- SA_* is a Safe Area, WT_* is a town Warp Terminal. Only actors
-- currently streamed in can be seen, which is a real limit: if nothing is
-- loaded nearby, the mod says so and does nothing rather than teleporting
-- you somewhere arbitrary.
--
-- In town you have a Warp Terminal already, so if the nearest thing is a
-- WT_ (or nothing is in range at all), this deliberately does nothing.

local CONFIG = {
    TELEPORT_KEY = Key.{TELEPORT_KEY},
    -- Ignore anything further away than this (cm). 0 = no limit.
    MAX_DISTANCE = {MAX_DISTANCE},
    -- Land slightly above the terminal so you don't spawn inside its mesh.
    Z_OFFSET = {Z_OFFSET},
}

local NAME = "{MOD}"
-- UE4SS key binds fire on UE4SS's OWN thread, not the game thread. UObject
-- work from the wrong thread silently does nothing -- which is why the EXP
-- grant, the town-chest fill and the enemy kill all "ran" and changed
-- nothing. Every working community mod for this game (DropRateScaling,
-- Norescue, AutoRipost) wraps its object work in ExecuteInGameThread; so do
-- these now.

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

RegisterKeyBind(CONFIG.TELEPORT_KEY, function()
    ExecuteInGameThread(function()
        local hero = FindFirstOf("RODHeroCharacter")
        if not hero or not hero:IsValid() then log("no hero — are you in-game?"); return end

        local here = hero:K2_GetActorLocation()
        local best, bestId, bestDist = nil, nil, nil

        local ok, terminals = pcall(function() return FindAllOf("RODActivatableTerminalBase") end)
        if not ok or not terminals then log("no terminal actors loaded"); return end

        for _, t in ipairs(terminals) do
            pcall(function()
                if not t:IsValid() then return end
                local id
                if t.ID then id = t.ID:ToString() end
                if not id or id == "" or id == "None" then return end
                -- SA_ only. WT_ is a town warp terminal, which you don't need
                -- this for, and anything else isn't a safe area.
                if string.sub(id, 1, 3) ~= "SA_" then return end

                local loc = t:K2_GetActorLocation()
                -- Unplaced actors read (0,0,0). Teleporting to the world origin
                -- would drop you into the void.
                if loc.X == 0 and loc.Y == 0 and loc.Z == 0 then return end

                local dx, dy, dz = loc.X - here.X, loc.Y - here.Y, loc.Z - here.Z
                local dist = math.sqrt(dx * dx + dy * dy + dz * dz)
                if not bestDist or dist < bestDist then
                    best, bestId, bestDist = loc, id, dist
                end
            end)
        end

        if not best then
            log("no Safe Area terminal is currently loaded nearby — nothing to teleport to")
            return
        end
        if CONFIG.MAX_DISTANCE > 0 and bestDist > CONFIG.MAX_DISTANCE then
            log(string.format("nearest Safe Area (%s) is %.0fm away, beyond the limit — not teleporting",
                bestId, bestDist / 100))
            return
        end

        local moved = pcall(function()
            hero:K2_SetActorLocation({ X = best.X, Y = best.Y, Z = best.Z + CONFIG.Z_OFFSET },
                false, {}, true)
        end)
        if moved then
            log(string.format("teleported to %s (%.0fm away)", bestId, bestDist / 100))
        else
            log("teleport failed — the game may be blocking movement right now (cutscene, combat lock)")
        end
    end)
end)

log("loaded — press the hotkey to teleport to the nearest Safe Area")
