-- {MOD} — list and dump warp terminals / safe areas
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- The game treats these as one family (ARODActivatableTerminalBase); the id
-- prefix is what tells them apart:
--     SA_*  Safe Area  (field rest point, opens the fast-travel map)
--     WT_*  Warp Terminal (town)
--     TG_*  quest terminal
-- so they're grouped by prefix rather than lumped together, and the dump can
-- be uploaded on the Build Dashboard to fill in coordinates the static export
-- doesn't contain.
--
-- Terminals only exist while their streaming cell is loaded, so this reports
-- what's ACTUALLY in memory. A dump from one spot is partial by nature -- the
-- upload endpoint MERGES, so sweeping several areas accumulates.

local CONFIG = {
    LIST_KEY = Key.{LIST_KEY},
    DUMP_KEY = Key.{DUMP_KEY},
    OUTPUT_FILE = "TerminalLocations.json",
}

local NAME = "{MOD}"
local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function kindOf(id)
    local p = string.sub(id, 1, 3)
    if p == "SA_" then return "safe_area" end
    if p == "WT_" then return "warp_terminal" end
    if p == "TG_" then return "quest_terminal" end
    return "terminal"
end

local function collect()
    local out = {}
    local hero = FindFirstOf("RODHeroCharacter")
    local here = hero and hero:IsValid() and hero:K2_GetActorLocation() or nil

    local ok, terminals = pcall(function() return FindAllOf("RODActivatableTerminalBase") end)
    if not ok or not terminals then return out end

    for _, t in ipairs(terminals) do
        pcall(function()
            if not t:IsValid() then return end
            local full = t:GetFullName()
            if string.find(full, "Default__", 1, true) then return end   -- template, not placed

            local id = ""
            pcall(function() if t.ID then id = t.ID:ToString() end end)
            if id == "" or id == "None" then return end

            local l = t:K2_GetActorLocation()
            -- An actor at exactly (0,0,0) hasn't had its transform applied yet.
            if l.X == 0 and l.Y == 0 and l.Z == 0 then return end

            local dist
            if here then
                local dx, dy, dz = l.X - here.X, l.Y - here.Y, l.Z - here.Z
                dist = math.sqrt(dx*dx + dy*dy + dz*dz)
            end
            out[#out + 1] = {
                id = id, kind = kindOf(id),
                x = l.X, y = l.Y, z = l.Z, dist = dist,
                chunk = string.match(full, "([A-Za-z0-9_]+)%.%1:") or "",
            }
        end)
    end
    table.sort(out, function(a, b) return (a.dist or 1e12) < (b.dist or 1e12) end)
    return out
end

RegisterKeyBind(CONFIG.LIST_KEY, function()
    ExecuteInGameThread(function()
        local list = collect()
        if #list == 0 then log("no terminals loaded here"); return end
        log(string.format("%d terminal(s) loaded:", #list))
        for _, t in ipairs(list) do
            log(string.format("  %-14s %-28s %s", t.kind, t.id,
                t.dist and string.format("%.0fm", t.dist / 100) or ""))
        end
    end)
end)

RegisterKeyBind(CONFIG.DUMP_KEY, function()
    ExecuteInGameThread(function()
        local list = collect()
        local parts = {}
        for _, t in ipairs(list) do
            parts[#parts + 1] = string.format(
                '  {"id":"%s","kind":"%s","chunk":"%s","x":%.3f,"y":%.3f,"z":%.3f}',
                t.id, t.kind, t.chunk, t.x, t.y, t.z)
        end
        local f = io.open(CONFIG.OUTPUT_FILE, "w")
        if not f then log("could not write " .. CONFIG.OUTPUT_FILE); return end
        f:write('{\n "capturedBy": "' .. NAME .. '",\n "count": ' .. #list ..
                ',\n "terminals": [\n' .. table.concat(parts, ",\n") .. '\n ]\n}\n')
        f:close()
        log(string.format("wrote %d terminal(s) -> %s (upload it on the Build Dashboard)", #list, CONFIG.OUTPUT_FILE))
    end)
end)

log("loaded — list key prints terminals; dump key writes them to JSON")
