-- {MOD} — Town Chest: set every stackable item to 999 when you open it
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- Grounded in the game's own SDK:
--   ARODChestBase::BP_OnOpenUI()          -- fires when the town chest UI opens
--   URODAvatarItemManager : Items, MaterialItems, EquipmentItems
--                                          -- TArray<FPossessItem>
--   FPossessItem -> FStorageItemData -> FItemDataBase -> FItemDataSimple
--       FItemDataSimple : EItemCategory Category, int32 ItemId
--       FItemDataBase   : int32 Num          <- the quantity we set
--
-- The town chest is ARODChestBase (the field treasure boxes are a
-- different class, ARODTBoxBase) -- which is exactly the distinction the
-- gimmick dump already surfaced as "chest_town" vs "chest".
--
-- EQUIPMENT IS DELIBERATELY EXCLUDED. The request was "all Items and
-- Materials", and that's also the only version that makes sense: weapons
-- and armour are unique instances with their own upgrade state, and a
-- stack of 999 of one sword is not a thing the game models. Consumables
-- and materials are the stackable categories. Set INCLUDE_EQUIPMENT if
-- you want to try it anyway -- it's off by default because it's more
-- likely to corrupt an inventory than to help.
--
-- "even if over 999": the quantity is SET, not clamped or topped up, so a
-- stack already above 999 comes DOWN to 999 as asked.

local CONFIG = {
    QUANTITY = {QUANTITY},
    INCLUDE_ITEMS = {INCLUDE_ITEMS},
    INCLUDE_MATERIALS = {INCLUDE_MATERIALS},
    INCLUDE_EQUIPMENT = {INCLUDE_EQUIPMENT},

    -- Also do it on a hotkey, so you can trigger it without opening the
    -- chest (and so you have a fallback if the hook ever stops firing
    -- after a game patch).
    MANUAL_KEY = Key.{MANUAL_KEY},
}

local NAME = "{MOD}"
-- UE4SS key binds fire on UE4SS's OWN thread, not the game thread. UObject
-- work from the wrong thread silently does nothing -- which is why the EXP
-- grant, the town-chest fill and the enemy kill all "ran" and changed
-- nothing. Every working community mod for this game (DropRateScaling,
-- Norescue, AutoRipost) wraps its object work in ExecuteInGameThread; so do
-- these now.

local function log(m) print(string.format("[%s] %s\n", NAME, tostring(m))) end

local function itemManager()
    local ok, im = pcall(function() return FindFirstOf("RODAvatarItemManager") end)
    if ok and im and im:IsValid() then return im end
    return nil
end

local function fillArray(arr, label)
    local changed = 0
    local ok = pcall(function()
        local n = #arr
        for i = 1, n do
            local entry = arr[i]
            if entry then
                local before = entry.Num
                if before ~= CONFIG.QUANTITY then
                    entry.Num = CONFIG.QUANTITY
                    changed = changed + 1
                end
            end
        end
    end)
    if not ok then
        log("could not walk " .. label .. " (array shape differs from the SDK?)")
        return 0
    end
    return changed
end

local function fillAll(trigger)
    local im = itemManager()
    if not im then
        log("no item manager — are you in-game?")
        return
    end

    local total = 0
    if CONFIG.INCLUDE_ITEMS then total = total + fillArray(im.Items, "Items") end
    if CONFIG.INCLUDE_MATERIALS then total = total + fillArray(im.MaterialItems, "MaterialItems") end
    if CONFIG.INCLUDE_EQUIPMENT then total = total + fillArray(im.EquipmentItems, "EquipmentItems") end

    log(string.format("%s — set %d stack(s) to %d", trigger, total, CONFIG.QUANTITY))
end

-- Hook the town chest's own open event. This is the real trigger: it
-- fires exactly when the chest UI comes up, so the numbers are already
-- 999 by the time the list draws.
local hooked = pcall(function()
    RegisterHook("/Script/ROD.RODChestBase:BP_OnOpenUI", function()
        -- Hook callbacks also need the game thread for object work.
        ExecuteInGameThread(function() fillAll("town chest opened") end)
    end)
end)

if hooked then
    log("hooked RODChestBase:BP_OnOpenUI")
else
    log("could NOT hook BP_OnOpenUI — the hotkey still works. (If the town chest is a "
        .. "Blueprint subclass, the hook path may need to be its BP class instead.)")
end

RegisterKeyBind(CONFIG.MANUAL_KEY, function()
    ExecuteInGameThread(function()
        fillAll("hotkey")
    end)
end)

log(string.format("loaded — open the town chest (or press the hotkey) to set items/materials to %d",
    CONFIG.QUANTITY))
