-- {MOD} — log levels, worlds and actor spawns as the game loads them
-- Generated by the ROD Database Toolkit's Lua Scripting presets.
--
-- This is the mod that makes the OTHER work possible. Everything hard in
-- this project has come down to one question -- "what does the game
-- actually do, and when?" -- and until now we've answered it by reading a
-- static export and inferring. This watches it happen.
--
-- WHAT IT LOGS
--   * Map loads       -- every travel to a new level (which is how we
--                        learned the Character Creator is its own map,
--                        PL_CharacterMake, rather than a widget).
--   * Streaming levels -- sublevels/cells as they stream IN and OUT. This
--                        is the thing that makes chest sweeping awkward:
--                        gimmicks only exist while their cell is loaded,
--                        so seeing the cells appear tells you exactly when
--                        a dump will capture something.
--   * New actors       -- optionally, actors as they are constructed:
--                        enemy spawns, barriers, gimmicks, chests. Filter
--                        by name so it doesn't drown you (every tree and
--                        rock is an actor too).
--
-- Everything is written to WorldLog.txt next to the UE4SS dll as well as
-- the console, because the interesting event is always the one that just
-- scrolled past.

local CONFIG = {
    LOG_MAP_LOADS = {LOG_MAP_LOADS},
    LOG_STREAMING_LEVELS = {LOG_STREAMING_LEVELS},
    LOG_NEW_ACTORS = {LOG_NEW_ACTORS},

    -- Only log actors whose class name contains one of these. Empty = all
    -- (which is a firehose -- every mesh, light and volume in the level).
    ACTOR_FILTERS = { {ACTOR_FILTERS} },

    -- How often to re-check which streaming levels are loaded (ms).
    STREAM_POLL_MS = {STREAM_POLL_MS},

    OUTPUT_FILE = "WorldLog.txt",
}

local NAME = "{MOD}"
local file = nil

local function stamp()
    return os.date("%H:%M:%S")
end

local function log(m)
    local line = string.format("[%s] %s", stamp(), tostring(m))
    print(string.format("[%s] %s\n", NAME, line))
    if not file then
        file = io.open(CONFIG.OUTPUT_FILE, "a")
    end
    if file then
        file:write(line .. "\n")
        file:flush()   -- flush every line: a crash is exactly when you most
                       -- want the log, and buffered lines die with the process
    end
end

-- --- Map loads ---------------------------------------------------------
if CONFIG.LOG_MAP_LOADS then
    -- UE4SS gives us the engine's own map-travel callbacks. This is how you
    -- catch the game changing worlds without polling for it.
    local okPre = pcall(function()
        RegisterLoadMapPreHook(function(Engine, World)
            local name = "?"
            pcall(function() name = World:get():GetFullName() end)
            log("MAP LOADING -> " .. name)
        end)
    end)
    local okPost = pcall(function()
        RegisterLoadMapPostHook(function(Engine, World)
            local name = "?"
            pcall(function() name = World:get():GetFullName() end)
            log("MAP LOADED  -> " .. name)
        end)
    end)
    if not (okPre or okPost) then
        log("map-load hooks unavailable in this UE4SS build — falling back to polling")
    end
end

-- --- Streaming levels --------------------------------------------------
-- These are the cells that decide whether a chest/gimmick actor exists at
-- all. Watching them appear tells you when a sweep will actually capture.
local seenLevels = {}

local function pollStreamingLevels()
    local ok, levels = pcall(function() return FindAllOf("Level") end)
    if not ok or not levels then return end
    for _, lv in ipairs(levels) do
        pcall(function()
            if not lv:IsValid() then return end
            local n = lv:GetFullName()
            if not seenLevels[n] then
                seenLevels[n] = true
                log("LEVEL STREAMED IN: " .. n)
            end
        end)
    end
end

-- --- New actors --------------------------------------------------------
local function wanted(className)
    if #CONFIG.ACTOR_FILTERS == 0 then return true end
    for _, f in ipairs(CONFIG.ACTOR_FILTERS) do
        if string.find(className, f, 1, true) then return true end
    end
    return false
end

if CONFIG.LOG_NEW_ACTORS then
    -- NotifyOnNewObject fires as objects are constructed. Registering on
    -- AActor catches every actor subclass, and the filter keeps it usable.
    local ok = pcall(function()
        NotifyOnNewObject("/Script/Engine.Actor", function(obj)
            pcall(function()
                local cls = obj:GetClass():GetFName():ToString()
                if not wanted(cls) then return end
                local loc = ""
                pcall(function()
                    local l = obj:K2_GetActorLocation()
                    loc = string.format("  @ %.0f, %.0f, %.0f", l.X, l.Y, l.Z)
                end)
                log("SPAWN " .. cls .. loc)
            end)
        end)
    end)
    if not ok then
        log("NotifyOnNewObject unavailable — actor spawn logging is off")
    end
end

if CONFIG.LOG_STREAMING_LEVELS then
    LoopAsync(CONFIG.STREAM_POLL_MS, function()
        pollStreamingLevels()
        return false
    end)
end

log("=== " .. NAME .. " started ===")
log(string.format("maps:%s streaming:%s actors:%s",
    tostring(CONFIG.LOG_MAP_LOADS), tostring(CONFIG.LOG_STREAMING_LEVELS),
    tostring(CONFIG.LOG_NEW_ACTORS)))
